### ISSUE TITLE
AttributeError: 'FixtureClosureNode' object has no attribute 'remove'

### ISSUE THREAD

**Issue by smarie** [smarie/python-pytest-cases#116]
From https://github.com/pytest-dev/pytest-bdd/issues/380

I need to better understand why removing a fixture from the closure is needed though :)

**Comment by smarie** [comment]
This should be easily fixed when #111  is fixed

**Comment by The-Compiler** [comment]
> I need to better understand why removing a fixture from the closure is needed though :)

I don't know exactly! FWIW the code was originally implemented (as `request.fixturenames.remove(arg)`) in https://github.com/pytest-dev/pytest-bdd/commit/d3928c7e4d5162ef764fb7365caf2471111d9a3c.
