### ISSUE TITLE
Installing pytest-cases seems to break Black

### ISSUE THREAD

**Issue by chinghwayu** [smarie/python-pytest-cases#122]
After installing, upon running
`coverage run --source myproj -m pytest`
For every file, it will error with:
`E       AttributeError: 'BlackItem' object has no attribute 'funcargs'`

setup.cfg is
```
[tool:pytest]
addopts = --black
```
This is with pytest-black installed.

**Comment by smarie** [comment]
Indeed, thanks for reporting @chinghwayu !
