### ISSUE TITLE
How to use builtin Pytest fixtures

### ISSUE THREAD

**Issue by 6Hhcy** [smarie/python-pytest-cases#134]
I want to pass `tmp_path_factory ` from Pytest into my case. What is the recommended way to do this?

,Thanks

**Comment by 6Hhcy** [comment]
just needed to pass it to the fixture, like in regular pytest. Apologies.

**Comment by smarie** [comment]
Thanks for the feedback @6Hhcy , absolutely no problem with such reports ! it builds up the knowledge base :)
