### ISSUE TITLE
parameterise on a fixture that returns an iterable

### ISSUE THREAD

**Issue by albertjan** [smarie/python-pytest-cases#141]
I feel this is possible but I'm just not getting my head around it.

We have a bunch of acceptance tests and in one of them I have a service that tells me the options to test for based on the user's region. Something like this:

```
@fixture
def languages_supported(client) -> Iterable[str]: #client is a fixture
     return client.get_languages()

@pytest_parametrize_plus('lang', something_something(languages)) 
def test_service_responds_in_language(service_client, lang): # client is a fixture
    assert service_client.get(lang) == lang
```

I've tried using cases, I looked at the case generator, but all of them require the list of things to test for to be defined in the decorator. Or am I missing something 😄 thanks!

**Comment by smarie** [comment]
Hi @albertjan thanks for posting this ! If I understand your question correctly, you wish to parametrize tests based on the iterable returned by a fixture. Unfortunately this is not possible with `pytest` by design : see my answer [here in stackoverflow](https://stackoverflow.com/a/56865893/7262247)

**Comment by albertjan** [comment]
Alright thanks, I figured as much but there was a little spark of hope it would be possible with pytest-cases 😄.

**Comment by smarie** [comment]
:) The issue is that the list of test nodes can not grow dynamically. So the entire list of parameters must be available during the test collection phase. You can therefore work around this limitation quite easily:

```python
# create a client in the module root
my_client = ...

# use it to list your parameters
all_languages = my_client.get_languages(...)

# define your session fixture as "just" returning the module-level variable
@pytest.fixture(scope='session')
def client():
    global my_client
    return my_client

# use the list of parameters to parametrize your tests
@pytest_parametrize_plus('lang', all_languages) 
def test_service_responds_in_language(client, lang): # client is a fixture
    assert client.get(lang) == lang
```
