### ISSUE TITLE
Using parametrization on cases function makes the id of the test case run to start with an unexpected hyphen symbol

### ISSUE THREAD

**Issue by romanponomaryov** [smarie/python-pytest-cases#142]
Hi @smarie!
I've noticed that if I apply `@parametrize `or `@pytest.mark.parametrize` to my cases function like this:

```python
@pytest.mark.parametrize('dummy_amount', [1, 0, -1])
def case_amount(dummy_amount):
    return dummy_amount

@parametrize_with_cases('dummy_amount', cases=".")
def test_amount(dummy_amount):
    <some code here>
```
then in the test report instead of 
```
PASSED ....test_amount[1]
PASSED ....test_amount[0]
PASSED ....test_amount[-1]
```
I get
```
PASSED ....test_amount[-1]
PASSED ....test_amount[-0]
PASSED ....test_amount[--1]
```

Moving case function to another file makes no difference.
Is parametrizing cases even a proper way? I just don't want to create a separate case function for every case, and sometimes the test values are packed in separate variables, so I need a way to iterate through them. Parametrizing seems like a good solution, but then I'm getting the described problem.

Thanks!

**Comment by romanponomaryov** [comment]
I've looked into it, and it seems these lines are to blame:
https://github.com/smarie/python-pytest-cases/blob/1d33f2fc5b703b98e83fa538b9c961247153ff91/pytest_cases/case_parametrizer_new.py#L299-L300

If I change it so the case where there is no case_id is being accounted for:
```python
        return tuple(lazy_value(partial(case_fun, **c.funcargs), id="%s-%s" % (case_id, c.id) if case_id else "%s" % c.id, marks=c.marks)
                    for c in meta._calls)
```
my problem goes away

**Comment by smarie** [comment]
I @romanponomaryov , which version of `pytest-cases` do you use ? Indeed if I execute your original code, I can not reproduce the issue. I get:

```
test_issue_142.py::test_amount[amount-1] 
test_issue_142.py::test_amount[amount-0] 
test_issue_142.py::test_amount[amount--1]
```

**Comment by romanponomaryov** [comment]
Hey @smarie , sorry for misinforming you.
The problem indeed only happens with one additional option - prefix. Otherwise I get the same result as you.
So, my code looks like this:
```python
@pytest.mark.parametrize('dummy_amount', [1, 0, -1])
def case_amount(dummy_amount):
    return dummy_amount

@parametrize_with_cases('dummy_amount', prefix="case_amount", cases=".")
def test_amount(dummy_amount):
    <some code here>
```
I am using the latest version of pytest-cases (2.3.0)
As for the prefix option - I need to use it, because in my cases file there are many case functions, each needed for different test function in my tests file.

**Comment by smarie** [comment]
Now I understand and I am able to reproduce it. I fixed it for next version: `"<empty_case_id>"` will appear when the case id is empty.

**Comment by romanponomaryov** [comment]
Hi @smarie ,
I've managed a workaround for my problem, but only partly. There is still something there I don't understand, so if you could please help me or explain where to look.
So, I have a workaround for parametrizing single values:

```python
@parametrize('dummy_amount', [0, 3, -4, -1])
def case_list(dummy_amount):
    return dummy_amount

remove_redundant_hyphen = lambda **args: "-".join(str(v)[1:] for n, v in args.items())

@parametrize_with_cases('dummy_amount', prefix="case_list", cases='.', idgen=remove_redundant_hyphen)
def test_list(dummy_amount):
    assert True
```

This works ok and I get in report:
```
PASSED ...test_experiment.py::test_list[0]
PASSED ...test_experiment.py::test_list[3]
PASSED ...test_experiment.py::test_list[-4]
PASSED ...test_experiment.py::test_list[-1]
```
But this does not work with parametrizing more than one value:
```python
@parametrize('dummy_amount, exp_amount', [(0, 3), (-4, -1), (5, 8)])
def case_tuples(dummy_amount, exp_amount):
    return dummy_amount, exp_amount

remove_redundant_hyphen = lambda **args: "-".join(str(v)[1:] for n, v in args.items())

@parametrize_with_cases('dummy_amount, exp_amount', prefix="case_tuples", cases='.', idgen=remove_redundant_hyphen2)
def test_tuples(dummy_amount, exp_amount):
    assert True
```
and I get in report:

```
PASSED ...test_experiment.py::test_tuples[-0-3]
PASSED ...test_experiment.py::test_tuples[--4--1]
PASSED ...test_experiment.py::test_tuples[-5-8]
```
while I'm aiming at getting same result as with `@pytest.mark.parametrize`, namely:
```
PASSED ...test_experiment.py::test_tuples[0-3]
PASSED ...test_experiment.py::test_tuples[-4--1]
PASSED ...test_experiment.py::test_tuples[5-8]
```
The output in report seems to be not affected at all, no matter how I change the function provided to `idgen` or if I introduce `ids` parameter into `@parametrize_with_cases` , like this:
```python
tuples = [(0, 3), (-4, -1), (5, 8)]

@parametrize_with_cases('dummy_amount, exp_amount', prefix="case_tuples", cases='.', ids=[str(x) for x in tuples])
```

**Comment by smarie** [comment]
Hi @romanponomaryov , I think that there was some misunderstanding here. The easiest workaround until the new release ships is just to use a non empty case id. So the case function names should have a suffix after the prefix, for example:

```python
@parametrize('dummy_amount', [0, 3, -4, -1])
def case_list_a(dummy_amount):  # <------------ notice the name here
    return dummy_amount

def case_list_b():  # <------------ notice the name here
    return 12

@parametrize_with_cases('dummy_amount', prefix="case_list_", cases='.')
def test_list(dummy_amount):
    assert True
```

Yields:

```
test_tmp.py::test_list[a-0] 
test_tmp.py::test_list[a-3] 
test_tmp.py::test_list[a--4] 
test_tmp.py::test_list[a--1] 
test_tmp.py::test_list[b] 
```

I do not think that there is a need to remove the case function name from the test id in the particular situation where there is a single case function. Do you ? That would require quite cumbersome/specific code for something that does not bring much to the end user in my opinion..

**Comment by romanponomaryov** [comment]
Hey @smarie 
"I do not think that there is a need to remove the case function name from the test id in the particular situation where there is a single case function." - for backwards compatibility with `@pytest.mark.parametrize` it would be ideal to have an option to mimick `@pytest.mark.parametrize` output. I think this is mostly useful for other plugins, as in my case.
In my specific case, I need this for pytest-dependency plugin. It ensures that my other test that depends on the `test_tuples` only runs if all the cases in the `test_tuples` passed, otherwise it skips. So this plugin takes the test ids of the `test_tuples` successful runs and compares them to the precompiled list of expected values of these runs and makes a decision. This precompiled list is made independently by a fixture function (this solution is given in pytest-dependency [docs](https://pytest-dependency.readthedocs.io/en/stable/advanced.html#depend-on-all-instances-of-a-parametrized-test-at-once)) , and the plugin depends on the output of `@pytest.mark.parametrize`, so it expects the same format of test ids. That's why I am trying to get the test ids made only with the values used in the test case because it's what `@pytest.mark.parametrize` outputs.
