### ISSUE TITLE
parametrize implementation doesn't support infinite generators

### ISSUE THREAD

**Issue by plammens** [smarie/python-pytest-cases#148]
Per the `pytest` documentation, the `ids` parameter of `pytest.mark.parametrize` also accepts a (possibly infinite) generator of ids, e.g. `(f"foo{i}" for i in itertools.count())`. (This has the advantage of not having to care about keeping the lenght of `argvalues` and `ids` in sync.) However, `pytest_cases`'s custom managing of ids tries to consume the iterator all at once, hence causing the program to hang indefinitely at the collection stage:

https://github.com/smarie/python-pytest-cases/blob/ae942d7bd997c0c97cfa886f7d76fd2029167a80/pytest_cases/common_pytest.py#L227

Reproducible example:

```python
import itertools as itt

import pytest
import pytest_cases


@pytest_cases.fixture()
@pytest.mark.parametrize("x", [1, 2, 3], ids=(f"x{i}" for i in itt.count()))
def my_fixture(x):
    return x

def test_foo(my_fixture):
    pass
```

This happens even if we replace `pytest.mark.parametrize` with `pytest_cases.parametrize`.

**Comment by smarie** [comment]
Thanks @plammens ! Indeed, good catch. I'll fix this now

**Comment by smarie** [comment]
Actually could you please provide a reproducible example that enters into this particular case ? Indeed it does not seem to happen
with a basic test:

```python
import itertools
from pytest_cases import parametrize

@parametrize("foo", [1, 2], ids=("foo{%s}" % i for i in itertools.count()))
def dummy(foo):
    pass
```

I guess that it happens with some custom `pytest.param` or other things.

**Comment by plammens** [comment]
Ah! Should have mentioned that this happened only when parametrizing a fixture (i.e. `pytest_cases.fixture` on top of `pytest.mark.parametrize` decorators). I've edited the issue to add a reproducible example.

**Comment by smarie** [comment]
Thanks @plammens for your reactivity. Fixing this now
