### ISSUE TITLE
Add a parameter to `parametrize_with_cases` to re-compute cases for every invocation

### ISSUE THREAD

**Issue by plammens** [smarie/python-pytest-cases#149]
I think it could be useful to add a way to ensure that test cases are recomputed each time they appear in a test invocation (node). For example, if a function is parametrized with the cartesian product of two sequences of arguments `x` and `y`, there should be a way that for each different value of `y`, each value of `x` is computed afresh, and viceversa. This allows one to use mutable case objects.

Currently, if we use mutable objects as case values, their state will leak through from invocation to invocation:

```python
import pytest_cases


def x():
    return []


@pytest_cases.parametrize("value", [0, 1])
def y(value):
    return value


@pytest_cases.parametrize_with_cases("y", cases=y)
@pytest_cases.parametrize_with_cases("x", cases=x)
def test_foo(x, y):
    print(x, y)
    assert x == []
    x.append("something")
```

<details>

```none
============================================================================================== test session starts ==============================================================================================
platform win32 -- Python 3.9.0, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: C:\Users\Paolo
plugins: cases-2.5.0
collected 2 items                                                                                                                                                                                                

..\..\..\AppData\Roaming\JetBrains\PyCharm2020.2\scratches\scratch.py .F                                                                                                                                   [100%]

=================================================================================================== FAILURES ====================================================================================================
________________________________________________________________________________________________ test_foo[x-y-1] ________________________________________________________________________________________________

x = ['something'], y = 1

    @pytest_cases.parametrize_with_cases("y", cases=y)
    @pytest_cases.parametrize_with_cases("x", cases=x)
    def test_foo(x, y):
        print(x, y)
>       assert x == []
E       AssertionError: assert ['something'] == []
E         Left contains one more item: 'something'
E         Use -v to get the full diff

..\..\..\AppData\Roaming\JetBrains\PyCharm2020.2\scratches\scratch.py:17: AssertionError
--------------------------------------------------------------------------------------------- Captured stdout call ----------------------------------------------------------------------------------------------
['something'] 1
============================================================================================ short test summary info ============================================================================================
FAILED ..\..\..\AppData\Roaming\JetBrains\PyCharm2020.2\scratches\scratch.py::test_foo[x-y-1] - AssertionError: assert ['something'] == []
========================================================================================== 1 failed, 1 passed in 0.47s ==========================================================================================
```

</details>

**Comment by smarie** [comment]
This can be reproduced with the underlying `lazy_value` util:

```python
from pytest_cases import parametrize, lazy_value

def x():
    return []

@parametrize("y", [0, 1])
@parametrize("x", [lazy_value(x)])
def test_foo(x, y):
    print(x, y)
    assert x == []
    x.append("something")
```

Now the tricky thing is that a cache mechanism was precisely requested by #143 , so that another plugin could inspect the value without calling the method again.

And in general I think that both behaviours (cached and not cached) might be desirable.

Maybe we could have the following policy:

 - make sure that the method is called at every test node to avoid leakage by default as you suggest

 - keep the cache mechanism so that other plugins can easily access the last retrieved value (#143 so that @TheCaffinatedDeveloper is happy)

 - let users use `@lru_cache` or another mechanism of their choice if they wish a particular case function to have a cache ? Or provide a specific new argument in `@case(cache=True)` ? Not sure about the best choice here.

What do you think @plammens and @TheCaffinatedDeveloper ?

**Comment by TheCaffinatedDeveloper** [comment]
@plammens @smarie This is definitely an interesting scenario. The first thought that comes to mind is that mutating objects can lead itself to some unintended behavior. If I needed to accomplish this, I would probably do something with deepcopy like:

```
import copy
from pytest_cases import parametrize_with_cases

def x():
    return []

@pytest_cases.parametrize_with_cases("y", cases=y)
@pytest_cases.parametrize_with_cases("x", cases=x)
def test_foo(x, y):
    mutable_x = copy.deepcopy(x)
    print(x, y)
    assert mutable_x == []
    mutable_x.append("something")
```

With that said, I like the idea of allowing the flexibility @smarie proposed with adding caching via a decorator. It is also explicit and readable that tells others "this should not be recalculated".

**Comment by plammens** [comment]
> Maybe we could have the following policy:
> 
> * make sure that the method is called at every test node to avoid leakage by default as you suggest
> * keep the cache mechanism so that other plugins can easily access the last retrieved value (#143 so that @TheCaffinatedDeveloper is happy)
> * let users use `@lru_cache` or another mechanism of their choice if they wish a particular case function to have a cache ? Or provide a specific new argument in `@case(cache=True)` ? Not sure about the best choice here.
> 
> What do you think @plammens and @TheCaffinatedDeveloper ?

I think that sounds good! Providing flexibility to do both seems the best solution. And I also think that calling the case function each time is a sensible default, since one would expect each invocation to be completely independent from the others.

Regarding the caching mechanism, I'd just go for the simpler solution of letting users do it themselves if their case functions need to be cached for performance—after all this is easily done with a decorator like `lru_cached` or the more general [`cachetools.cached`](https://pypi.org/project/cachetools/), so there's not too much value gained by implementing it in `pytest_cases`. But if you believe it isn't adding too much complexity then using a special argument in the `case` decorator also makes sense to me. In that case I'd say `cache=False` would be the better default—i.e. guaranteed correctness by default instead of performance by default.

**Comment by smarie** [comment]
Thanks @TheCaffinatedDeveloper and @plammens for this quick feedback ! After sleeping on this I came to the same conclusion as @plammens : it is so easy for users to implement the cache themselves with `@lru_cache` that it is not worth trying to do it for them. I'll implement this now, and add a doc section
