### ISSUE TITLE
Use @pytest.mark.usefixtures decorator for case function

### ISSUE THREAD

**Issue by arut-grigoryan** [smarie/python-pytest-cases#152]
Can I somehow use decorator @pytest.mark.usefixtures for case function? I prefer it when the fixture sets some system state but returns nothing.

**Comment by smarie** [comment]
Thanks @arut-grigoryan . I am not familiar with this decorator. Can you please provide an example showing that it is not properly taken into account ? That would ease the process of creating the test and adding support for it. Thanks in advance !

**Comment by arut-grigoryan** [comment]
**@pytest.mark.usefixtures** in pytest documentation - https://docs.pytest.org/en/stable/fixture.html#use-fixtures-in-classes-and-modules-with-usefixtures

Example:
Test flask application. There is a variable in the config that sets the validation of incoming data. The fixture **validationOff** disables validation but returns nothing. Essentially sets the state of the system.

test file
```
@pytest.fixture
def validationOff():
    app.config["VALIDATION"] = False
    yield
    app.config["VALIDATION"] = True
```
case file
```
@case(id="first")
def case_foo(validationOff):
    ...
@case(id="second")
@pytest.mark.usefixtures("validationOff")
def case_bar(self):
    ...
```
In 'first' case used validationOff fixture. In 'second' case not used validationOff fixture.

**Comment by arut-grigoryan** [comment]
It was very fast, thank you very much

**Comment by smarie** [comment]
you're welcome ! The implem is not very optimal but if it does the job for now, it is good :) 
It should be on pypi by now by the way
