### ISSUE TITLE
Can't get cartesian product of cases depending on fixture

### ISSUE THREAD

**Issue by plammens** [smarie/python-pytest-cases#157]
In the same way that this
```python
import sys
import pytest_cases


@pytest_cases.parametrize("x", [1, 2, 3])
def case_x(x):
    return x


@pytest_cases.parametrize("y", [1, 2, 3])
def case_y(y):
    return y


@pytest_cases.parametrize_with_cases("x", cases=case_x)
@pytest_cases.parametrize_with_cases("y", cases=case_y)
def test_foo(x, y):
    print(f" {x, y}", file=sys.stderr, end="")
```
tests on the cartesian product of `x` and `y`, I would have expected this
```python
import sys
import pytest_cases


@pytest_cases.fixture()
@pytest_cases.parametrize("x", [1, 2, 3])
def fixture(x):
    return x


def case_fixture(fixture):
    return fixture


@pytest_cases.parametrize_with_cases("fixture1", cases=case_fixture)
@pytest_cases.parametrize_with_cases("fixture2", cases=case_fixture)
def test_foo(fixture1, fixture2):
    print(f" {fixture1, fixture2}", file=sys.stderr, end="")
```
to test on the cartesian product of `[1, 2, 3]`. However, when I run the test it only runs for `1-1`, `2-2` and `3-3`, i.e. it's using the same fixture instance for both parameters.

Is this the expected behaviour?

I also tried this:
```python
@pytest_cases.parametrize(y=(pytest_cases.fixture_ref(fixture),))
@pytest_cases.parametrize(x=(pytest_cases.fixture_ref(fixture),),)
def test_foo(x, y):
    print(f" {x, y}", file=sys.stderr, end="")
```
with the same result.

Basically I'm looking for a way to get the cartesian product of a fixture with itself.

**Comment by smarie** [comment]
This is the expected behaviour indeed. In `pytest`, when a fixture is used twice in the same test node (directly or indirectly), its parameters are used only once.

The only way I know to do this in pytest is to have two distinct parametrized fixtures (that may reuse the same lower-leverl root fixture or routine)

**Comment by plammens** [comment]
Thanks, I guess I'm still very much confused when I should use fixtures, cases, parameters, or something else 😅
