### ISSUE TITLE
Referencing a specific case function within a class

### ISSUE THREAD

**Issue by plammens** [smarie/python-pytest-cases#159]
What is the correct way to reference a specific case function that is part of a class (for case grouping)?

For example, this
```python
import pytest_cases


class CaseGroup:
    def case_x(self):
        return 1


@pytest_cases.parametrize_with_cases("x", cases=CaseGroup.case_x)
def test_spam(x):
    pass
```
doesn't work because `CaseGroup.case_x` is an unbound method and there's nothing to fill the `self` parameter with (pytest complains that there is no fixture named `self`).

One way maybe would be to instantiate the case group before referencing the method:
```python
@pytest_cases.parametrize_with_cases("x", cases=CaseGroup().case_x)
def test_spam(x):
    pass
```
although this looks quite ugly.

Another would be to use `@staticmethod`:
```python
class CaseGroup:
    @staticmethod
    def case_x1():
        return 1

    @staticmethod
    def case_x2():
        return 2


@pytest_cases.parametrize_with_cases("x", cases=CaseGroup.case_x1)
def test_specific_x(x):
    pass
```
Is this supported? If so, should the `staticmethod` decorator always be the topmost? 

In any case, if we have to do this for every case function, it becomes cumbersome. Perhaps it would be useful to have a metaclass in `pytest-cases` that automatically makes every function in the class definition body a static method, since case classes are essentially just a namespace. This could also be useful in the future to add any other features to case classes.

**Comment by smarie** [comment]
I can definitely find a way to directly support `CaseGroup.case_x`. Wow you're testing every single possibility here :) thanks for being so active ! 

Note: that particular issue could be quite easy to handle in a PR, look for the file `cases_parametrizer_new.py` if you're interested. You'll see that I create partial functions when cases are collected inside a class, for example.

**Comment by plammens** [comment]
> I can definitely find a way to directly support `CaseGroup.case_x`. Wow you're testing every single possibility here :) thanks for being so active !

Hahaha it's more about having no idea what I'm doing so I have to restructure my test code every five seconds, and every time I do so I find something 😆 

> Note: that particular issue could be quite easy to handle in a PR, look for the file cases_parametrizer_new.py if you're interested. You'll see that I create partial functions when cases are collected inside a class, for example.

Thanks, I'll take a look!

**Comment by plammens** [comment]
Meanwhile, I have seen that currently all static and class methods get skipped silently:

https://github.com/smarie/python-pytest-cases/blob/8febdeeb52f6dcfcb54aa1e8e7d966427d030ad5/pytest_cases/case_parametrizer_new.py#L613-L615

I wanted to use static methods so I could refer to test functions without instantiating the class. I expected that to work fine, but to be fair it's not mentioned in the docs whether that is supported or not. It took quite some time to find out why suddenly the number of tests dropped by a few hundred 😆 What was the rationale behind this?

**Comment by smarie** [comment]
> to be fair it's not mentioned in the docs whether that is supported or not. It took quite some time to find out why suddenly the number of tests dropped by a few hundred 😆 What was the rationale behind this?

:) thanks for challenging me on this. Well, there is definitely no rationale: this was a quick way to get the nominal use cases work and not care too much. I need to fix this indeed, I'll open a dedicated issue

**Comment by smarie** [comment]
Hi @plammens I finally managed to take a stab at this. I was not fond of users having to use an explicit metaclass, so I went down through the hell of determining the host and binding status of all kind of python functions :)

It seems to work though, I'll release this in 3.4.0 shortly.
