### ISSUE TITLE
question: skipping cases?

### ISSUE THREAD

**Issue by shaunc** [smarie/python-pytest-cases#173]
Thank you for your library! I am interested in using it to organize the tests for my machine learning library. (I am now using ad-hoc methods to combine fixtures with parametrize.)

Running on some cases, however, is very slow; I don't want to always have to run these cases.

For my tests themselves, I have defined the following decorator:
```python
def skip_slow(test_fct: Callable) -> Callable:
    """
    Skip test unless TEST_SLOW in environment.
    """
    return pytest.mark.skipif(
        not os.environ.get("TEST_SLOW", "").lower() == "true",
        reason="skip slow tests",
    )(test_fct)
```

Can I use this or something similar with test cases, to optionally skip them?

**Comment by shaunc** [comment]
Oops -- found [the doc](https://smarie.github.io/python-pytest-cases/#pytest-marks-skip-xfail) that answers my question!

**Comment by smarie** [comment]
Perfect ! Thanks for the feedback @shaunc

**Comment by shaunc** [comment]
Already partially working! Great package; thanks @smarie!

Only thing that tripped me up in the beginning: I was creating my fixtures in modules of a package, whose "__init__" was importing them. Then when I used fixtures, which depended on other fixtures which were annotated with @parametrize_by_cases, I would get weird "not found" errors -- I thought that chaining case-annotated fixtures wasn't working perhaps.

Of course, the problem turned out to be that new names are generated in module scope, and I needed to import these into the package __init__. It would be nice to have that in the docs somewhere (in a "warning box" perhaps :)) -- I understand that pytest is magical and pytest_cases doubles down, but putting things at module scope should still be documented.... they could run into other symbols, for instance, and the user wouldn't know what was happening....

**Comment by smarie** [comment]
> they could run into other symbols, for instance, and the user wouldn't know what was happening

Actually I have put some safeguards here to generate unique names. But you're right, your point is the same as the one we discussed in #158. @plammens opened #174 for it.

More generally the new engine #170 should remove all hidden fixture creation, as it was a good way to get me started but has a lot of side effects. Thanks for the feedback !

**Comment by shaunc** [comment]
Is there a good workaround for typing these hidden fixtures, btw?
```
packages/emm/tests/fixtures/__init__.py:2: error: Module 'tests.fixtures.generated_features' has no attribute 'basic'
```
[and a bunch more such errors from mypy...]

**Comment by smarie** [comment]
> Is there a good workaround for typing these hidden fixtures, btw?

I'm afraid not :( in general I would not recommend using typing/mypy on the test folder, but of course this is a personal decision. If you wish you can open a dedicated issue on this topic (in that case please try to provide a minimal reproducible example) so that users can try to help/have a look

**Comment by shaunc** [comment]
ok ... well for the moment doing `# type ignore` on fixture import. Hopefully these hidden fixtures will go away. I'll open an issue if necessary on the new implementation in the new year! :)

**Comment by smarie** [comment]
ok, thanks!
