### ISSUE TITLE
Use only same parameters for fixture and tests

### ISSUE THREAD

**Issue by ftruzzi** [smarie/python-pytest-cases#175]
Hi,

I'm very new to both pytest and pytest-cases and I'm trying to set up tests with the following structure (example):

A few test cases:

```python
def case_query_no_results():
    return {
        "query": "query that yields no results",
        "validate_result_func": lambda x: len(x) == 0,
    }

def case_query_results():
    return {
        "query": "normal query",
        "validate_result_func": lambda x: len(x) <= 99
    }

def case_query_long_results():
    return {
        "query": "long query",
        "validate_result_func": lambda x: len(x) > 99
    }
```

A fixture that fetches search results from an API based on the test cases:

```python
@fixture
@parametrize_with_cases("test_case")
def search_results(test_case):
    # get results based on test_case["query"]
    return results
```

Test cases that leverage the search fixture:

```python
@parametrize_with_cases("test_case")
def test_search_results_length(search_results, test_case):
    assert test_case["validate_result_func"](search_results) is True

@parametrize_with_cases("test_case")
def test_something_else(search_results, test_case):
  # blah blah
```

It looks like all test combinations are being created, for example, there is a case where `test_search_results_length` is processing the `case_query_results` test case but it's receiving `search_results` from `case_query_no_results`. What I would like to do here is make sure that the `test_case` variable and the `search_result` fixture result always refer to the same test case in a given test invocation.

I was able to make this work with `@parametrize`, e.g.:

```python
test_cases = (
    ["query that yields no results", lambda x: len(x) == 0],
    ["normal query", lambda x: len(x) <= 99],
    ["long query", lambda x: len(x) > 99]
)

@parametrize('search_results, validate_len', test_cases, indirect=["search_results"])
def test_results_len(search_results, validate_len):
    assert validate_len(search_results) is True
```

I know I'm probably missing something here, but what's the correct way of doing this with pytest-cases?

Thanks!

**Comment by ftruzzi** [comment]
Sorry, not sure why I didn't see it -- the solution was to parametrize the fixture only and have it return both the result and the test case:

```python
@fixture
@parametrize_with_cases("test_case")
def search_results(test_case):
    # get results based on test_case["query"]
    return results, test_case

def test_search_results_length(search_results):
    results, test_case = search_results
    assert test_case["validate_result_func"](search_results) is True
```

wondering if this is the best way or a good practice though. Thanks!

**Comment by smarie** [comment]
Thanks @ftruzzi for the feedback ! Indeed it is not always easy to get the fixture design right.

There is no "official" method but I would do the following thinking: start from the test and be very clear about what you need. Here your test need two things: the test "case" (the query) and the search results. If everything is independent and does not need to be reused, you can create it with parametrize. So your initial design is to have a parametrize for the "case" and another parametrize for the "search results".

Then you realize that this is not possible because the "search results" also need access to the case at hand. So the case at hand needs to be reused by **both** the search results **and** the test. This indicates that you need to create a fixture for the test case. Finally since you create a fixture for the test case, then the "search results" cannot be a parameter anymore, it has to be a fixture too. Final proposal:

```python
from pytest_cases import fixture, parametrize_with_cases

def case_query_no_results():
    ...

def case_query_results():
    ...

def case_query_long_results():
    ...

@fixture
@parametrize_with_cases("test_case", cases=".")
def my_test_case(test_case):
    """ A fixture containing the test case """
    return test_case

@fixture
def search_results(my_test_case):
    """ A fixture creating the results for the current test case """
    # get results based on test_case["query"]
    return results

def test_search_results_length(search_results, my_test_case):
    """ A test needing both the results and the test case """
    assert my_test_case["validate_result_func"](search_results) is True
```

Let me know if this works for you

**Comment by shaunc** [comment]
Works for me! :) ... I think I figured this out once before, but was having trouble with some new tests and ended up here. I might suggest the documents for @fixture -- say -- (and/or ref in parametrize_with_cases) should give a similar example.

**Comment by smarie** [comment]
Perfect, thanks for the feedback @shaunc  ! Closing this ticket then. @ftruzzi feel free to reopen if the various answers do not entirely solve your initial issue
