### ISSUE TITLE
Support pytest plugins that modify the fixture closure list

### ISSUE THREAD

**Issue by HMaker** [smarie/python-pytest-cases#176]
I tried to parametrize a test function marked by [pytest-asyncio](https://github.com/pytest-dev/pytest-asyncio)
```python
import random
import pytest
from pytest_cases import parametrize_with_cases


def sum(a, b):
    return a + b

@pytest.fixture
def random_num():
    return random.randint(0, 65543)

def case_1(random_num: int):
    return 1, random_num, 1 + random_num

def case_2(random_num: int):
    return 2, random_num, 2 + random_num

@pytest.mark.asyncio
@parametrize_with_cases('case', cases='.')
async def test_sum_of(case):
    a, b, c = case
    assert sum(a, b) == c

```
but `pytest_cases` raises `NotImplementedError: When fixture unions are present, inserting a fixture in the closure is non-trivial. Please report this so that we can find a suitable solution for your need.`

That works with [pytest-lazy-fixture](https://github.com/TvoroG/pytest-lazy-fixture)
```python
@pytest.mark.asyncio
@pytest.mark.parametrize('case', pytest.lazy_fixture((
    'case_1',
    'case_2'
)))
async def test_sum_of(case):
    a, b, c = case
    assert sum(a, b) == c
```

Thanks in advance.

**Comment by smarie** [comment]
thanks for the feedback @HMaker  ! I'll have a look

**Comment by smarie** [comment]
(Unfortunately I only fixed half of the issue yet)

**Comment by smarie** [comment]
@HMaker can you confirm that this new version 3.2.0 works for you ? thanks !

**Comment by smarie** [comment]
Up @HMaker  ?

**Comment by HMaker** [comment]
> Up @HMaker ?

Sorry for late answer, I ran the code I sent above and the same error still happens. Steps to reproduce (linux env):
```bash
mkdir -p /temp/test-pytest
cd /tmp/test-pytest
python3 -m venv --prompt pytest venv
source venv/bin/activate
pip install pytest pytest-asyncio pytest-cases
cat << EOF > test_case.py
import random
import pytest
from pytest_cases import parametrize_with_cases


def sum(a, b):
    return a + b

@pytest.fixture
def random_num():
    return random.randint(0, 65543)

def case_1(random_num: int):
    return 1, random_num, 1 + random_num

def case_2(random_num: int):
    return 2, random_num, 2 + random_num

@pytest.mark.asyncio
@parametrize_with_cases('case', cases='.')
async def test_sum_of(case):
    a, b, c = case
    assert sum(a, b) == c
EOF
pytest test_case.py
```
That error happened with Python 3.9.1 and following deps from `pip freeze`
```
attrs==20.3.0
decopatch==1.4.8
iniconfig==1.1.1
makefun==1.9.5
packaging==20.9
pluggy==0.13.1
py==1.10.0
pyparsing==2.4.7
pytest==6.2.2
pytest-asyncio==0.14.0
pytest-cases==3.2.1
toml==0.10.2
```
Did not you run that code before closing the issue?

**Comment by smarie** [comment]
Lol it seems that pytest-asyncio inserts it at the beginning of the closure instead of putting it at the end (append). Maybe they changed behaviour in the lastest version ? Or I just dreamed it, but I thought I tested it locally...

This will make it a little bit more complex to fix. I'll have to have a go again, thanks a LOT for reporting it !

**Comment by HMaker** [comment]
pytest-asyncio 0.14.0 was released in Jun 23, 2020 as shown in its [pypi page](https://pypi.org/project/pytest-asyncio/), so I was  using that version (actually it's set to "*" in requirements file, i.e. unpinned) when reported that error for the first time. Anyway, thanks for your attention.

**Comment by smarie** [comment]
Yes I saw that. Sorry, I don"t know what have happened. Anyway, I'll try to fix this now.

**Comment by smarie** [comment]
Confirmed: I was using `pytest-asyncio 0.10.0` locally, and the fix works correctly for it.

**Comment by smarie** [comment]
I made it work. Here are the current limitations, that should hopefully be quite tolerant to most existing plugins:

 - Removing a fixture from the closure using `closure.remove(fixture_name)` is supported as long as the  `fixture_name` or one of its dependencies is not a fixture union (no tree)
 - Appending a fixture to the closure with `closure.append(fixture_name)` or `closure.insert(len(closure), fixture_name)` is supported in **all cases** (even if `fixture_name` or one of its dependencies is a fixture union and induces a tree with closure partitions))
 - Prepending a fixture to the closure with `closure.insert(0, fixture_name)` is supported as long as the  `fixture_name` or one of its dependencies is not a fixture union (no tree)
 - Inserting a fixture anywhere else in the closure with `closure.insert(i, fixture_name)`  is not supported, as it is non-trivial and context-dependent to understand "where and if" in all tree nodes this should have an impact.

I'll try to cut a release soon.

**Comment by smarie** [comment]
@HMaker I managed to finally release version 3.3.0 that contains the fix. Sorry for the delay, I had to migrate from Travis to Github Actions to get [my CI/CD pipelines back](https://github.com/smarie/python-pytest-cases/actions).

Could you let me know if this is working for you ? Just in case the tested configuration is slightly different from the one you're using.
