### ISSUE TITLE
Fixtures defined in conftest.py not found

### ISSUE THREAD

**Issue by WIRUT** [smarie/python-pytest-cases#178]
Hello!

Thanks for making pytest-cases! I believe it's exactly what I'm looking for in writing my tests. Alas, I am still new to python and I am running into an issue. I'm not quite sure if this is related to #174. 

Example:

```
from pytest_cases import parametrize_with_cases, case

class TestCases:
    @case(tags='abc')
    def case_abc(self, fixture_obj):
        return set(self.get_response(fixture_obj).split())

    # Helper Methods
    @staticmethod
    def get_response(fixture_obj):
        response = fixture_obj.send_command(
            [
                "ls -a"
            ]
        )
        return response['Status']

class TestStructure:
    @staticmethod
    @parametrize_with_cases("actual_response", cases=TestCases, has_tag='abc')
    def test_a(actual_response):
        expected_response = "Success"
        assert actual_response is expected_response
```

The `fixture_obj` has a method that makes a remote request. It is defined in the `conftest.py` module and contains the necessary methods to make such a request and subsequent ones.

However, when running this test I also get the error where the `fixture_obj` is not recognized.

```test setup failed
file test_a.py, line 55: source code not available
file <makefun-gen-9>, line 1: source code not available
file <makefun-gen-7>, line 1: source code not available
E       fixture 'fixture_obj' not found
>       available fixtures: aws, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, check, clusterinfo, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

<makefun-gen-7>:1

Assertion failed
```
This isn't an issue if I were to create individual tests for each case (thus Pytest recognizes the fixture). Is this something that's intended?

**Comment by WIRUT** [comment]
PEBKAC. My conftest.py was inside a sub-folder.

**Comment by smarie** [comment]
Thanks @WIRUT for both opening and closing this ticket ! Glad you found a solution to your problem, that may also help others if they run into the same issue.
