### ISSUE TITLE
Question: how to select case in test using derived fixtures

### ISSUE THREAD

**Issue by shaunc** [smarie/python-pytest-cases#188]
I have a case class with a number of cases, from which a series of fixtures (corresponding to steps in a machine-learning pipeline) are derived. For tests where I want to run all the cases, this is quite convenient. But is there a way to mark/select for a particular case so for a given test I can use a "downstream" fixture and only compute a particular case for that test? 

Currently, I am checking which case I have along with the fixture, and raising skip if I have the wrong one. But I'm hoping there is a better way that avoids computation of all the alternative fixtures when I am focusing on a particular test or set of tests which only make sense for a subset of the cases.

Thanks!

**Comment by shaunc** [comment]
Aha:
```python
class MyCases:

    @case(tags=["foo"])
    def case_foo():
        ...

    @case(tags=["bar"])
    def case_bar():
        ...

@fixture
@parametrize_with_cases("case", cases=MyCases)
def f1(case):
    ...

@fixture
def f2(f1):
    ...

@parametrize_with_cases("case", cases=MyCases, has_tag="foo")
def test_f2_only_foo(case, f2):
    """
    Fixtures generated and run only when "foo" is defined if only this test is run.
    """
    ...
```
The one improvement I might suggest is to allow:
```
@parametrize_with_cases(None, cases=MyCases, has_tag="foo")
def test_f2_only_foo(f2):
    ...
```
As I really don't care about the case. Indeed a specialized decorator would be nice, e.g.:
```
@limit_to_cases(cases=MyCases, has_tag="foo")
```
:)

**Comment by shaunc** [comment]
Oops! I spoke too soon. Seems that fixtures for other cases run after all. I know that I can focus on a particular case for a particular test using a fully-specified ID, but I'm not sure how to make this work for a subset of tests/cases, and would like to have this happen programmatically.

**Comment by smarie** [comment]
I am not sure that this pytest design is the right one to reach your goal - although I have no specific proposal to suggest here :(

 - the first thing to ask yourself is "do I need this single fixture here" ? Indeed it seems to be the bottleneck. I tend to separate the data cases from the algorithm cases, from other fixtures, so that each they can be freely combined when needed and separated when not needed / when a subset is needed. This is a bit like in object-oriented design, when a good practice is to avoid "deep" inheritance trees, and rather have a set of "mix-in" classes with no inheritance, that you can combine as needed.

 - once this design topic is solved, there are two technical elements that may help you :

    - For "strict" incremental testing you may wish to look at [the `pytest.mark.incremental` example](https://docs.pytest.org/en/stable/example/simple.html#incremental-testing-test-steps) or my [pytest-steps plugin](https://smarie.github.io/python-pytest-steps/), although I really think that your "steps" are more complex that the ones those simple approaches support

    - otherwise, there is a notion of "indirect parametrization" in pytest explained [here](https://docs.pytest.org/en/stable/example/parametrize.html#indirect-parametrization). Of course it is not well suited to pytest-cases since you do not want to re-provide a list of parameter values. However if this is **really** needed, maybe you can experiment with this and propose a way to integrate it in pytest cases. Note however that everytime I saw a code using indirect parametrization in the past, there was a way to re-design the tests/fixtures/params to remove it. So personally I never use it: too unreadable.

I hope these help !

**Comment by shaunc** [comment]
Apropos your first point:

Here, the cases will be different datasets, and the fixtures precomputed steps along a machine learning pipeline. As they are compute intensive (relatively -- even for teensy example datasets), I am eager to avoid computing twice. I could separate out the logic:
```python
def f1_fct(a_case):
    ...
def e2_fct(a_f1):
    ...
@fixture
@parametrize_with_cases("case", cases=MyCases)
def f1(case):
    return f1_fct(case)

@fixture
def f2(f1):
    return f2_fct(case)
```
... then I could create a new fixture for `f2` that just takes the case(s) I want. But this doesn't avoid recomputation of `f1` and `f2` when I am running more tests than just `test_f2_only_foo`. ... is there something I'm missing? I could create my own custom caching system, but ... well... that would be a lot of work, and I'd be recreating what fixtures are supposed to be. (BTW these are session scoped).

---

Apropos incremental/steps: this looks promising. Hmm... perhaps I can use marks instead of tags, and in conftest check if all tests have a common mark ("foo_only") ... or some subset of common marks, and if so skip fixtures who don't belong to the chain extending from that mark. If I skip the "base fixture" I guess pytest will be clever enough to skip dependents automatically. I haven't delved into pytest-steps enough to figure out to what extent it provides helpful machinery for this.

Apropos complexity: currently the pipeline is a DAG... but it does factor cleanly into cases -- so a tensor product of DAGs.

Thank you for your help! You can close or not depending on whether you think there is anything pytest-cases (or its documentation) could do to address similar cases.

**Comment by shaunc** [comment]
Aha -- so you put a mark into markers with the case name. So I can mark my test:
```python
@pytest.mark.featureset("foo")
def test_f2_only_foo(f2):
    ...
```
Then in contest.py:
```python
def pytest_collection_modifyitems(config, items):
    ...
    save = []
    for item in items:
        if "featureset" in item.keywords:
            fs_mark = [
                m for m in item.own_markers if m.name == "featureset"
            ][0]
            featureset_name = fs_mark.args[0]
            if featureset_name in item.keywords:
                save.append(item)
        else:
            save.append(item)
    items[:] = save
```
... and the unwanted branches are pruned! :)

My question is -- can I rely on the "internal" of the case name appearing in `item.keywords`?

**Comment by smarie** [comment]
A few comments:

 - concerning session fixtures: I was thinking the same as you but pytest does not guarantee that a session-scope fixture is not created several times, in case of parametrization. So "caching" is not really the feature provided by pytest fixtures, think of it as "sharing resources that take time to setup/teardown" (a database connection, etc.). A fixture is probably rather a resource, not an intermediate result. But a fixture can be a handy injector for a `global` module-scoped variable that would be truly unique and would provide the caching feature. That's how I would rather do it if I were in this situation. If you want this shared unique object provide strict caching you can have it use `joblib.memory` (for file based) or `lru_cache` (for memory based).

```
class MyResultsCache:
     ...

_cache = MyResultsCache()

@fixture
def cache():
    global _cache
    return _cache
```

 - Concerning marks, here is another plugin I wrote that can be handy to filter based on marks, not sure how it is relevant to your situation  https://smarie.github.io/python-pytest-pilot/ 

> My question is -- can I rely on the "internal" of the case name appearing in item.keywords?

What do you mean ? That the pytest mark appears in item.keywords ? It seems to be a core pytest mechanism and appears in the examples so I guess this is safe to use, yes.

**Comment by shaunc** [comment]
Thanks @smarie --

* session fixtures: in fact, the fixtures do depend on the cases, so they need to be created several times when we actually are running several cases. In my experience currently, they are created once per parameter setting/case. Just that I want to prevent creation if eventually I am going to skip the whole case.

In fact, when I delete the tests for the other cases, the fixtures are indeed not generated. So just what I wanted to achieve.

* marks: the question is whether I can count on the case name appearing in `item.keywords` (not my custom mark "featureset"). I'm not sure how it gets in there...

**Comment by smarie** [comment]
Concerning the case id availability:

 - if you have access to `item` in a `pytest` hook, you can access the current case name with `item.callspec.params[param_name].get_id()` where `param_name` is the name of the parameter filled with cases (typically, `'case'`).

 - the same can be done if you can access the `request` fixture: `request.node.callspec.params[case_param_name].get_id()`

To clarify my message above, I would suggest the following "no fixture" design by creating the same DAG as you currently create with fixtures, with plain old cached python functions:

```python
@lru_cache(-1)
def process_step_A(case):
    ...
    return ...


@lru_cache(-1)
def process_step_B(case):
    # here your DAG is made of explicit function calls to parents
    res = process_step_A(case)
    ...
    return ...


@parametrize_with_cases("case", ...)  # use the subset of cases relevant to this test
def test_a(case):
    # call the node in the DAG that is relevant to this test
    res = processB(case)
    ...

@parametrize_with_cases("case", ...)
def test_b(case):
    res = processA(case)
    ...
```

Since all nodes in the DAG are cached and the joblib or lru/cache automatically can detect that inputs are identical or not (based on a hash) and therefore reuse a cached output or trigger a new call, this should do the trick. See https://joblib.readthedocs.io/en/latest/memory.html#memory and https://docs.python.org/3/library/functools.html#functools.cache or https://docs.python.org/3/library/functools.html#functools.lru_cache


Since all functions are cached,

**Comment by shaunc** [comment]
Ah -- thanks! That clarifies your suggestion a lot. Hmm... ok: you might be right that doing it that way might be easier than "tricking" pytest into creating the fixtures appropriately.

**Comment by smarie** [comment]
The "how to get the id" part of your comments is worth a proper API/documentation though, so I opened a dedicated issue. 

Let me know when you have made some tests, if I can then close this issue or if you have more questions/suggestions.

**Comment by shaunc** [comment]
Now rewriting my "pipeline" fixture DAG. One issue I'm struggling with is side dependencies. So currently, if I have fixtures:
```
B[case] <= (A[case], X)
```
Where X is a non-case dependency, consumers of `B` don't have to worry about `X` -- `B` simply takes as a dependency. Of course, B can simply take X privately, but if X feeds into multiple other fixtures, and/or has some teardown, using the fixture machinery was convenient. Hmm... I guess I could turn the case into a big bag of all these dependencies.... My DAG, unfortunately, is rather big and bushy, and likely to want to keep on growing, so some sort of modular solution would be nice. Perhaps I should pass "request" back to the "non-fixture cache functions" so I can simply access any actual fixtures they want (I guess I could write a decorator which spread a list of names to function arguments...).

I'd be grateful for suggestions!

**Comment by shaunc** [comment]
Ok ... this is what I've come up with so far -- comments welcome!

I've created objects for the cases themselves, which are instances of:
```python
class CaseFixtures:
    """
    Collection of fixtures accumulated by featureset pipeline.
    """

    def __init__(self):
        self.fixtures = {}
        self.fixture_values = OrderedDict()

    def __getitem__(self, fixture_name: str) -> Any:
        """
        Return fixture value, finding and running fixture if needed.
        """
        if fixture_name not in self.fixtures:
            try:
                fixture = inspect.stack()[1][0].f_globals[fixture_name]
            except KeyError:
                raise KeyError(f"Couldn't find fixture {fixture_name}")
            # NB if not really "case"-taking fixture, this also could
            # cause an error. Currently we let the user figure it out.
            fixture_value = fixture(self)
            self.fixtures[fixture_name] = fixture
            self.fixture_values[fixture_name] = fixture_value
        return self.fixture_values[fixture_name]

    def __setitem__(self, fixture_name: str, value: Any):
        """
        Set fixture value explicitly.
        """
        self.fixture_values[fixture_name] = value

    def release_fixtures(self):
        """
        Teardown fixtures in reverse order.
        """
        for fix in reversed(self.fixtures.values()):
            if inspect.isgeneratorfunction(fix):
                try:
                    fix.next()
                except StopIteration:
                    pass

```
Cases are setup with initial data, still using a pytest fixture to trigger teardown:
```
def setup_feature_case(name, config, features):
    case = CaseFixtures()
    case["config"] = config
    case["features"] = features
    case["name"] = name
    try:
        yield case
    finally:
        case.release_fixtures()


@fixture(scope="session")
def feature_case_basic(config_0_session, features_0_session):
    yield from setup_feature_case(
        "basic", config_0_session, features_0_session
    )

...

class CasesFeature:
    """
    Cases for different feature sets, varying over two dimensions:
    * size: basic, small, med
    * dv type/strategy: categorical, qentropy
    """

    @case(tags=["basic", "categorical"])
    def case_basic(self, feature_case_basic):
        return feature_case_basic
    ...
```


I've actually got a disk-based cache (extending lrucache) which stores cached data with clear names, so I can cache fixture values between tests. (Adding a pytest flag to clear the cache):
```python
gen_cache = dcache.DCache(
    cache_dir=Path(__file__).parent / "cache", maxsize=1_000_000
)
```
And a decorator which specifies that fixtures are stored using function name (implicit) and case name:
```
def cache_case(f: Callable) -> Callable:
    """
    Decorator to cache case-accepting feature by case name.
    """
    return gen_cache.memoize(
        key=lambda case, *args, **kw: case["name"]
    )(f)
```

Then for new-style "fixtures" using cache:
```
@cache_case
def fx_training(case) -> xr.Dataset:
    """
    Training dataset for features.
    """
    config = case["config"]
    features = case["fx_features"]
    training = feature.create_training_from_features(config, features)
    return training
```

So a test can take just `case` (selecting tags appropriately), and "retrieve" from it fixtures it needs, which should be torn down in inverse order of creation. (Perhaps this is a little too magical as it uses caller's stack frame to retrieve fixture functions... but... the pytest magic of using function arguments I don't think I can tap into, so I need a separate way to do it.)

Still a work in progress as there is rather a lot of fixtures and tests to wade through.

... again ... suggestions welcome!

**Comment by smarie** [comment]
I still have trouble to understand the high-level use case without implementation-specific details. So far what I understand:

 - you have a DAG of processing steps operating on data
 - you have a bunch of tests that act on output of these steps

So far, using functions (not fixtures) with cache + tests works.

If I understand well, the thing that makes the above not suit your need is that the processing steps require additional resources, and therefore you would like these resources to be declared as fixtures. Can you confirm ?

Even in this case, do not forget that the "main" object in your tests is.... the test. So my first reaction would be that the test depends on whatever fixture(s) is needed by the DAG node it uses, and passes it as an argument. If this does not work for you, could you explain precisely why, maybe providing a minimalistic example showing the need ? I think that de-coupling the "resource" feature of fixtures (that you obviously wish to keep) from the "DAG" one (that you should probably not keep as it is not meant for this) is the key to an elegant/modular design here.

**Comment by shaunc** [comment]
> I think that de-coupling the "resource" feature of fixtures (that you obviously wish to keep) from the "DAG" one (that you should probably not keep as it is not meant for this) is the key to an elegant/modular design here.

That is one challenge. The other challenge is that the DAG can have pieces that are not session scoped.

You are right that, in theory, I could factor out all the resources, but in the case:

Resource_1...Resource_n -> [Snarl of DAG] -> test I have to pass back all the resources to all the fixtures in the DAG. This is hard to do uniformly because not all resources are needed for every DAG. Also, sometimes, the resources depend on init from things in the DAG. (e.g. the ML has its own disk cache -- now using the case name to separate; I could use a random name but makes post-mortem debugging a little more inconvenient....) I'd rather the tests focus on actual testing rather than being switchboards for resource provision.

I think this is resolved by making the case into an object and using it a proxy location for the resources. Given I have a case instance object, I can use it provide lazy initialization. The same strategy can be used for fixtures. This muddies the boundary again between resources that need special treatment and fixtures that wouldn't, but if it is working at all, it should be ok to use for both purposes. (AFAIK)

This also works for subscopes. I can use -- e.g. -- a module-scoped pytest fixture to put some things into the case instance and then take them out on cleanup.

The difference with default pytest fixtures comes down to:
1) now I can select what DAG(s) to build based on case tags
2) I can persistently cache based on case.

This is sort of how "class" scope in pytest might work, if it did work. Really I'm using the case as a custom scope, with sub-scopes (and selecting subsets of them using tags). If pytest supported such custom scopes (and I could coordinate them with cases) I wouldn't need to role my own.

**Comment by smarie** [comment]
@shaunc I'm doing a bit of backlog cleaning: closing this ticket in favor of #194 for backlog readability. Once #194 is fixed we may come back to this, if it does not fix your issue.

**Comment by smarie** [comment]
Hi @shaunc even if the `indirect` feature (#194) is not there yet, I think that you can solve your initial problem with the `current_cases` fixture now : https://smarie.github.io/python-pytest-cases/#c-accessing-the-current-case

With this you can skip tests conditionally based on the case id, case function/tags/marks, case parameters... See doc for details and examples
