### ISSUE TITLE
Helper function to get the current case id

### ISSUE THREAD

**Issue by smarie** [smarie/python-pytest-cases#189]
from #188 this arised and could benefit from a documented API

**Comment by shaunc** [comment]
Hmm... is this really working in case of multiple argument names? For parametrize in the case of multiple argument names, `argnames` might look like "a,b" ... but passing "a,b" as a string to this function doesn't seem the right thing.  (`main_fixture_style_template` comes out to be something like "foo_a,b"...).

**Comment by smarie** [comment]
Good point, I need to check this a little more in depth. Having a few minutes only to work on this every day makes it sometimes quite superficial :) thanks for the feedback !

**Comment by smarie** [comment]
@shaunc  I managed to finally release version 3.3.0 that contains the fix. Sorry for the delay, I had to migrate from Travis to Github Actions to get [my CI/CD pipelines back](https://github.com/smarie/python-pytest-cases/actions).
