### ISSUE TITLE
filter/skipif combination of cases from multiple parametrize_with_cases decorators

### ISSUE THREAD

**Issue by eavanvalkenburg** [smarie/python-pytest-cases#195]
Hi, loving the library! I have a instance where I create a large number of test cases based on a combination of multiple parametrize_with_cases, a simple example here:

in test_package_cases.py:
```python
def encrypted_encrypted():
    """Return a key for a encrypted test."""
    return KEY


def encrypted_unencrypted():
    """Return None for a unencrypted test."""
    return None


def proto_tcp():
    """Return TCP protocol."""
    return Protocol.TCP


def proto_udp():
    """Return UDP protocol."""
    return Protocol.UDP
```

and in test_package.py

```python
    @parametrize_with_cases("encrypted", prefix="encrypted_")
    @parametrize_with_cases("protocol", prefix="proto_")
    def test_encrypted_over_protocols(
        self,
        encrypted,
        protocol)
       
       <test code>

```

This is a simplified example of what I want to achieve (I have one test that has 5 parametrize_with_cases, with a total of 80 tests coming out of it, which I love!), but let's say I now want to exclude the test for TCP Encrypted, I would have expected either a Filter or using something like pytest.mark.skipif(protocol==TCP and encrypted is not None) to do this, but that doesn't seem to work, and in the filter doc, I seem to read that a filter only applies to a single parametrize call, so you couldn't use both variables there. 

The workaround right now is to skip in the code, but I don't really like that approach!

**Comment by eavanvalkenburg** [comment]
yeah, the get_current_case* isn't much easier then just using a if condition block against the actual parameters that were passed in because of the cases, so this will work for now, but would be cool if you guys think of something here, because that would make it much more explicit, to see a skipped in the log instead of a passed for those instances!

**Comment by shaunc** [comment]
I had this problem too, and I think I was mostly able to overcome it using tags. You can pass a list of tags to both case decorator and parametrize_with_cases. Tags seem mostly for inclusion rather than exclusion, (@smarie - how about boolean tag expression support?) but since you can tag with a list, with a little work you can often come up with a way to exclude. (e.g., "not_encrypted" tag, together with some "neutral" tag in other cases -- e.g. "all_protos" ...?)

**Comment by smarie** [comment]
> that would make it much more explicit, to see a skipped in the log instead of a passed for those instances!

If this is the point that bothers you, you can write `pytest.skip(msg)` in your `if` statement ! 

@shaunc thanks for adding your thoughts here ! The filtering features, with the new helper functions from @saroad2 (`filters` module, described in the very last paragraph of [this section](https://smarie.github.io/python-pytest-cases/#filters-and-tags)) indeed does the trick for a each `@parametrize_with_cases` independently. However @eavanvalkenburg 's issue is that he would like to make a filter based on a condition depending on **two** cases (crossing the two `@parametrize_with_cases` decorators) - this can not be adressed for now, and I'm not sure that using fixtures can be of any help here ?

**Comment by eavanvalkenburg** [comment]
Indeed crossing the decorator boundary is the issue! and thanks for the tip about the pytest.skip, didn't know that one, will use that for now, you can close this if you want (or keep it open in case you want to refer to it later as a feature)!

**Comment by shaunc** [comment]
@smarie -- two cases -- ah, sorry.

One could make new cases individual items of cross product in a pair, leaving some out, then gather together and unpack again to get fixtures running over the desired subset. A lot of writing to do manually, but perhaps a helper could automate.

**Comment by smarie** [comment]
@eavanvalkenburg I found a way for you to solve this issue: with the new fixture `current_cases` you can access the exact case function currently in use for each parameter. You can therefore do 

```python
if current_cases["a"] is case_a and current_cases["b"] is case_b:
    pytest.skip("This combination of cases does not make sense")
```

Note that cases used to parametrize a fixture appear in this dictionary too, but one level deeper (under the fixture name).

Let me know if this solves your problem, and I'll close the issue then.

**Comment by smarie** [comment]
@eavanvalkenburg I'll close this now, but feel free to reopen if this did not solve your issue !
