### ISSUE TITLE
fixture_ref not working with cached property/dataclass objects

### ISSUE THREAD

**Issue by davidstrouk** [smarie/python-pytest-cases#206]
Hello,

I would like to use the enhanced `parametrize` function to call fixtures within the parameters.

I have a dataclass object with some cached property:
```
@dataclasses_json.dataclass_json
@dataclasses.dataclass(frozen=True)
class A:
    ...

    @functools.cached_property
    def index(self):
        return ...
```

In tests file I have a fixture returning this object:
```
@pytest.fixture(scope="module")
def a():
    return A()
```

When using it in some parametrized tests, for example:
```
@pytest_cases.parametrize(
    "fixture_a",
    pytest_cases.fixture_ref('a'),
)
async def test_a(fixture_a):
    assert True
```

I'm getting the error
```
AttributeError: 'fixture_ref' object has no attribute 'index'
```

Any idea on what could cause this issue? My guess is that when creating the `fixture_ref` object, cached properties are not inherited.

**Comment by smarie** [comment]
Thanks for reporting this @davidstrouk ! I can not reproduce your issue :(
(apart from the fact that in this extract you forgot to wrap the fixture ref into a list)

Can you try to provide a minimal reproducible example ? Thanks in advance ! 
Oh by the way note that `fixture_ref` is now optional, using the fixture symbol works:

```python
@dataclasses_json.dataclass_json
@dataclasses.dataclass(frozen=True)
class A:
    @functools.cached_property
    def index(self):
        return 1

@pytest.fixture(scope="module")
def a():
    return A()

@parametrize("fixture_a", [a])
def test_a(fixture_a):
    assert isinstance(fixture_a, A)
```

This runs fine on my end

**Comment by davidstrouk** [comment]
Hello and thanks for your quick answer.
I guess this is the minimal reproducible example:
```python
import dataclasses
import functools

import dataclasses_json
import pytest
import pytest_cases


@dataclasses_json.dataclass_json
@dataclasses.dataclass(frozen=True)
class A:
    @functools.cached_property
    def index(self):
        return 1


@pytest.fixture(scope="module")
def a():
    return A()


@pytest_cases.parametrize("index_a", [pytest_cases.fixture_ref("a").index])
def test_a(index_a):
    assert index_a == 1
```

**Comment by smarie** [comment]
Indeed, you use `.index` on the `fixture_ref` so it does not work. If you wish to get the `.index`, then you should get it either in the fixture or in the test code. For example :

```python
@pytest.fixture(scope="module")
def a():
    return A().index

@parametrize("index_a", [fixture_ref("a")])
def test_a(index_a):
    assert index_a == 1
```

I'll close this now. Feel free to reopen if there is a different problem !

**Comment by davidstrouk** [comment]
When is the `fixture_ref` transforming the fixture variable into the real
object?

In my usecase I can't use the attribute in the fixture because I would like
to call a function that gets the object A and gets its index among other
things.

**Comment by smarie** [comment]
`@parametrize` is the one doing the job of injecting the right thing in the parameter. In presence of a `fixture_ref` (or a fixture symbol, directly), it will create a dependency between your test and that fixture, but just when the fixture ref is actually used (just for the test nodes with this parameter value). The fixture will be setup/teardown by pytest as usual, and injected into your function.

So for your need you should either 

 - create a second fixture depending on the first, and refer to it in the parametrize, or 
 - simply access the index and other attributes inside the test function body.

Note that a fixture can return a tuple, and if a fixture_ref is used to parametrize a tuple of argnames, the fixture contents will be unpacked:

```
@fixture
def bar()
    return 1, 2

@parametrize("a,b", [(3, 4), bar])
def test_foo(a, b):
    pass
```
