### ISSUE TITLE
ModuleNotFoundError when trying to reference class in @parametrize_with_cases

### ISSUE THREAD

**Issue by wonboyn** [smarie/python-pytest-cases#210]
Hi there,

I have a test function file "test_constants.py" and a test cases file "test_constants_cases.py" in the same directory.

In the test cases file I have defined a class called SmartBooleanTestCases with a bunch of functions such as:
`
    @case(id="Lower case true")
    def case_true_lower_case(self):
        return "true", None, True

    @case(id="Camel case true")
    def case_true_camel_case(self):
        return "True", None, True
`

In the test function file I am attempting to use the test case class as follows:
`
@parametrize_with_cases("value,default,expected", cases="SmartBooleanTestCases")
def test_smart_bool(value, default, expected):
    '''Test that smart_bool can handle various inputs'''
    assert smart_bool(value, default) == expected
`

When I run pytest it is reporting that the module SmartBooleanTestCases is not found.
If I remove the cases="SmartBooleanTestCases" from the parametrize decorator it runs fine.

I must be missing something obvious about how to reference the test case class.
Any help would be greatly appreciated.

Thanks

Tim

**Comment by smarie** [comment]
Thanks @wonboyn ! Simply import the class:

```python
from .test_constants_cases import SmartBooleanTestCases

@parametrize_with_cases("value,default,expected", cases=SmartBooleanTestCases)
```

**Comment by wonboyn** [comment]
Thanks for that.

**Comment by smarie** [comment]
You're welcome!
