### ISSUE TITLE
Using pytest marks with parametrize_with_cases? (or how to configure which cases are run from the command line?)

### ISSUE THREAD

**Issue by jannsta1** [smarie/python-pytest-cases#239]
Hi! Thanks for developing this great pytest plugin. 

I have been experimenting with using pytest-cases as a benchmarking aid. Now that I have built some test cases, I am interested in a method for running a subset of tests, ideally from the command line. This is for convenience during development, i.e. when I make a change to an algorithm I can run some quick tests to check a particular aspect of its performance while maintaining a more comprehensive set of tests for a full benchmarking process. My test sets are organised into classes, with each class containing 1 or more methods that generate datasets. For example:

``` python
class TestSet1:
    def data_set1(self):
        return data1
    def data_set2(self):
        return data2

class TestSet2:
    def data_set1(self):
        return other_data1
...
```

I thought a natural way of achieving my goal would be to add some markers in the `pytest.ini` file and then decorate the classes of test cases accordingly. e.g.:
``` python
@pytest.mark.t1
class TestSet1:
    def data_set1(self):
...
```
Then I could use `pytest test/benchmarking -m t1` to call just the first batch of tests.

Now I'm struggling to find a good way of using these marks in my `parametrize_with_cases` fixture.  Before implementing this feature, my dataset fixture was like:
```  python
@fixture
@parametrize_with_cases("msgs", cases=[TestSet1, TestSet2, ], prefix='data_')
def dataset(msgs):
    yield msgs
```
I find that all test cases are run if I keep this function as it is, regardless of the markers I pass to pytest. I also tried:

```  python
@fixture
@parametrize_with_cases("msgs",
                        cases=[
                            pytest.param(TestSet1, marks=pytest.mark.t1),
                            pytest.param(TestSet2, marks=pytest.mark.t2),
                        ], prefix='data_'
)
def dataset(msgs):
    yield msgs
```
But I find that the tests are always skipped with this approach, regardless of the markers I pass to pytest. I was wondering if you have any suggestions about how to adapt this code or implement this feature in general?

**Comment by smarie** [comment]
Thanks @jannsta1 for the feedback ! I developped pytest-cases originally for benchmarks creation actually :)

By the way once this ticket is solved, you might wish to look at [pytest-pilot](https://smarie.github.io/python-pytest-pilot/) to create markers that are easier to understand and use.

Now trying to better understand your issue, my first reaction (as I do not have the time to try today) would be: 

 - did you try putting the mark directly on the case function ? (decorate `def data_set1(self):` instead of the wrapping class). Indeed I do not know if putting it on the container class actually propagates well (this might be normal pytest behaviour, or something I did not reproduce correctly in pytest-cases - we'll have to check if it is true). 

 - does this happen also when `@parametrize_with_cases` is used to decorate the test function directly, not on a fixture ? Indeed the way I parametrize fixtures today is a hack of pytest, because by default their fixtures can only support a single parametrization

Thanks for the feedback again !

 -

**Comment by jannsta1** [comment]
Thanks for the very quick reply and the `pytest-pilot` suggestion, that indeed looks like another interesting pytest plugin. Moving some of the marker logic from conftest and making it more explicit would indeed be welcome.

I have now tried your initial suggestions. Unfortunately neither seemed to do the trick. 

- For the first suggestion, I tried decorating the class methods with `pytest.mark.XX`. I also tried taking the dataset generating methods outside of the test set class entirely (copying the method code to the same module but outside of the test set class) to see if this made any difference but the result was the same. In both cases the marks don't seem to have any bearing on the test function.
- For the second suggestion, unfortunately this also didn't change anything. Although making this switch means that I can get rid of an otherwise redundant fixture so I will probably keep this change!

I will try digging into the pytest-cases source code a bit to see if I can figure out a way forward. If you think  of anything in the meantime it would be great to hear from you.

Cheers!

**Comment by smarie** [comment]
Hi @jannsta1 , the first suggestion works for me :

```python
from pytest_cases import parametrize_with_cases

@pytest.mark.valid
def case_a():
    return 0

@parametrize_with_cases("a", cases=case_a)
def test_valid_marked_cases(a):
    assert True
```

**Comment by smarie** [comment]
Update: it also seems to work with fixtures:

```python
@fixture
@parametrize_with_cases("a", cases=[FooCases, case_valid, case_invalid])
def my_fix(a):
    return a

def test_valid_marked_cases(my_fix):
    assert my_fix
```

Leads to the exact same result as above.

Maybe you were not using the latest version of pytest-cases?

**Comment by jannsta1** [comment]
Hi @smarie. So having looked at your example code, the mistake I was making is that I assumed I would also have to *mark* the test function, i.e. the one decorated with `parametrize_with_cases`. Once I removed all marks from this function everything worked as per your example and exactly as desired so I will close the "issue".

Thank you for taking the time to look at this, it was very much appreciated! Now I will checkout that `pytest-pilot` repo you mentioned. I found out about `pytest-cases` via the [data science benchmark example](https://smarie.github.io/pytest-patterns/examples/data_science_benchmark/) so I am also using `pytest-harvest` and it looks like `pytest-pilot` could improve the way that I set the `test_synthesis` functions to always run regardless of what marks are set.

**Comment by smarie** [comment]
Great ! I personally use pytest-pilot to have some cases run for some python environments, and some others in other environments. Typically the cases representing the challenger algorithms.

Note that the example you refer to is a bit obsolete, I did not update it recently :( hopefully most of it will still be valid.

The "test_synthesis" function is really optional: you can instead write one partial csv results file at the end of the main test, and concatenate all of them later. However, you'll have to measure the execution time yourself and also grab the case ids/params (this can now easily be done using [the new `current_cases` fixture](https://smarie.github.io/python-pytest-cases/#d-accessing-the-current-case)).

Anyway, let me know if you run into some issue!

**Comment by jammer87** [comment]
I found this issue investigating a problem I was having getting class marks propagated to cases in the class. If the case is marked as a static method, the marks from the class won't be applied, unlike marks applied to classes containing test cases. For example:

```python
import pytest
from pytest_cases import parametrize_with_cases


@pytest.mark.thing
class MarkedCases:
    def case_one(self):
        return 1

    @staticmethod
    def case_two():
        return 2


@pytest.mark.thing
class TestClass:
    def test_one(self):
        pass

    @staticmethod
    def test_two():
        pass


@parametrize_with_cases('a', cases=MarkedCases)
def test_params(a):
    pass

```
```text
pytest --collectonly tests/demo_test.py -m thing
...
plugins: cases-3.6.5
collected 4 items / 1 deselected / 3 selected

<Module tests/demo_test.py>
  <Class TestClass>
      <Function test_one>
      <Function test_two>
  <Function test_params[one]>
```
test_params[two] is missing, but would be included if the staticmethod decorator was removed. Thought I'd leave this hear in case anyone else runs into the same thing.

**Comment by smarie** [comment]
Thanks ! This sounds like a bug so I created another issue for it
