### ISSUE TITLE
Refactored scope handling in pytest 7

### ISSUE THREAD

**Issue by The-Compiler** [smarie/python-pytest-cases#241]
Thanks to https://github.com/pytest-dev/pytest/discussions/9415, we found out that `pytest-cases` breaks with pytest 7.0.0rc1:

```pytb
  File "/home/florian/tmp/pytest-bisect/python-pytest-cases/src/pytest_cases/__init__.py", line 8, in <module>
    from .fixture_core1_unions import fixture_union, NOT_USED, unpack_fixture, ignore_unused
  File "/home/florian/tmp/pytest-bisect/python-pytest-cases/src/pytest_cases/fixture_core1_unions.py", line 26, in <module>
    from .common_pytest import get_fixture_name, is_marked_parameter_value, get_marked_parameter_values, pytest_fixture, \
  File "/home/florian/tmp/pytest-bisect/python-pytest-cases/src/pytest_cases/common_pytest.py", line 527, in <module>
    from _pytest.python import scopes as pt_scopes, Metafunc  # noqa
ImportError: cannot import name 'scopes' from '_pytest.python' (/home/florian/proj/pytest/src/_pytest/python.py)
```

this is due to this change: https://github.com/pytest-dev/pytest/pull/8913 - looks like scopes are now an enum in a new [scope.py](https://github.com/pytest-dev/pytest/blob/main/src/_pytest/scope.py).

**Comment by smarie** [comment]
Thanks @The-Compiler ! I have tried to fix it in a blind way (not being able to grab 7.0.0rc1 from pypi and being extremely lazy), based on the diff. Let me know if 3.6.7 does not fix the issue !
