### ISSUE TITLE
Cases parameter and cases module location

### ISSUE THREAD

**Issue by MarkoBox** [smarie/python-pytest-cases#252]
Hi,
This is a very useful package, thank you for putting in the effort to maintain it :)

I'm struggling a bit with cases parameter and defining proper folder structure. What would be correct way to achieve this:

test function:
@parametrize_with_cases("rule", cases="tests.integration.test_foo_cases.py")
def test_is_rule(rule):
...

test case inside test_foo_cases.py:
def case_foo():
    return True

With folder structure like this:
/tests
       /fixtures
           test_foo_cases.py
       /integration
           test_foo.py
       ....

This is raising ModuleNotFoundError. And if i point it at the module im getting "Skipped: got empty parameter set " error
What im doing wrong here?

**Comment by nor3th** [comment]
Hey @MarkoBox 

What worked well for me were relative imports. 
Example:
```
/tests/__init__.py
/tests/test_foo.py
/tests/cases/__init__.py
/tests/cases/test_foo_cases.py
```
test_foo.py:
```
...
@parametrize_with_cases("var", cases='.cases.test_foo_cases', prefix='case_')
def test(var):
   assert var == "foo"
```

test_foo_cases.py
```
def case_foo():
   return "foo"

def case_foo_bar():
   return "foobar"
```

Hope this helps

Regards

**Comment by smarie** [comment]
Indeed, relative imports are the way to go here. Thanks @nor3th !

Note that alternately you may import the module explicitly using whatever means you prefer, and pass the module object to the `cases` arg. I usually do not do this, as relative module passed as string is more convenient

**Comment by smarie** [comment]
@MarkoBox do you confirm that this worked for you ? If so I can then close the ticket

**Comment by MarkoBokic** [comment]
Yes it did, thank you.

**Comment by smarie** [comment]
Thanks !
