### ISSUE TITLE
pyright error: Argument missing for parameter on `parametrize`

### ISSUE THREAD

**Issue by BorjaEst** [smarie/python-pytest-cases#270]
I am getting the following error when I use [pyright](https://github.com/microsoft/pyright) to check typing `parametrize` function:

```bash
error: Argument missing for parameter "host_class_or_module" (reportGeneralTypeIssues)
error: Argument missing for parameter "fixtures_dest" (reportGeneralTypeIssues)
```

This errror is related to my piece of code:
```py
from pytest_cases import parametrize
class Authorized:
    @parametrize("path", example_paths)  # <----- here comes the error
    def case_ValidToken(self, path):
        return path, {"Authorization": f"Bearer something"}
```

**Comment by smarie** [comment]
Thanks @BorjaEst  ! I'll have a look

**Comment by smarie** [comment]
I created a PR that should hopefully fix this. Can you please confirm that it does the trick for you ?

**Comment by BorjaEst** [comment]
Thanks @smarie, I confirm that for my cases (and so the above) the PR fix the issue.

**Comment by smarie** [comment]
Super, thanks @BorjaEst ! I'll ship a release asap

**Comment by smarie** [comment]
It should be fixed in 3.6.12, available in a few minutes. Let me know if this works for you !

**Comment by BorjaEst** [comment]
Yes, it works. Thanks @smarie .

**Comment by smarie** [comment]
Thanks for the feedback !
