### ISSUE TITLE
`fixture` does not work with lambdas

### ISSUE THREAD

**Issue by vyasr** [smarie/python-pytest-cases#278]
First of all I want to say thanks for a great plugin! I've been making extensive use of it recently. I've found a few minor issues that I wanted to raise, so I wanted to say thank you first!

The problem that I'm running into is that `pytest_cases.fixture` does not support lambdas, but `pytest.fixture` does.

```
import pytest
import pytest_cases

globals()['fix'] = pytest.fixture(lambda: 42)  # Works
globals()['fix2'] = pytest_cases.fixture(lambda: 42)  # Doesn't work
```

For context, I am basically doing what is described in [this comment](https://github.com/pytest-dev/pytest/issues/2424#issuecomment-333387206) to dynamically generate fixtures, which is why using a lambda would be nice.

**Comment by smarie** [comment]
Hi @vyasr , thanks a lot for your positive feedback !

Would you mind letting us know the stacktrace and when it happens (module loading time or later ?)
Thanks in advance!

**Comment by smarie** [comment]
I tried on my side and if I use I get the following error at test collection time:

```python
..\.nox\tests-3-9-env-pytest-latest\lib\site-packages\makefun\main.py:629: in _make
    code = compile(body, filename, 'single')
E     File "<makefun-gen-1034>", line 1
E       def <lambda>(request):
E           ^
E   SyntaxError: invalid syntax
```

This is an error in `makefun`, not `pytest-cases`. It seems that it will be closed with this PR: https://github.com/smarie/python-makefun/pull/80

**Comment by vyasr** [comment]
Yes, that is the correct error and I can confirm that https://github.com/smarie/python-makefun/pull/80 fixes the error when I patch that onto the PYTHONPATH. Thanks! I searched through issues on this repo but I didn't recognize that it was coming from the other package!

**Comment by smarie** [comment]
This should now work with makefun 1.14. Do you confirm ?

**Comment by smarie** [comment]
Closing for now, but feel free to reopen @vyasr

**Comment by vyasr** [comment]
Apologies for the delayed response. Yes, I can confirm that the newest release of makefun solves the problem!

**Comment by smarie** [comment]
Thanks @vyasr !
