### ISSUE TITLE
Wrapper functions for cases that do not use `wraps` don't work

### ISSUE THREAD

**Issue by vyasr** [smarie/python-pytest-cases#280]
There are a few issues here, so I think it will be easiest to demonstrate with a sequence of examples since I don't know what the appropriate solutions are here for `pytest_cases`. We start with this code:
```
import functools
import pytest_cases

@pytest_cases.fixture
def one():
    return 1

def deco(func):
    def wrapper(one):
        return func(one=one)
    return wrapper

@deco
def case_one(one):
    return one

@pytest_cases.parametrize_with_cases("cs", cases=".")
def test_wrapped_case(cs):
    assert cs == 1
```
There are two problems that I observe now. First, in addition to needing the name to be assigned correctly in the `globals()` dict (which is necessary for all pytest fixtures), cases in `pytest_cases` also need the `__name__` being copied to the wrapper. Adding `wrapper.__name__ == func.__name__` addresses this problem. At this point, the above example works, but in my real use case the decorator is in a different module from the case function. That causes problems because `pytest_cases` uses the `__module__` attribute to [verify that the function is actually defined in the right module](https://github.com/smarie/python-pytest-cases/blob/main/src/pytest_cases/case_parametrizer_new.py#L799). Therefore, we need the wrapper to also have the same `__module__` as the wrapped function.

With those two fixes, the decorator becomes:
```
def deco(func):
    def wrapper(one):
        return func(one=one)
    wrapper.__name__ = func.__name__
    wrapper.__module__ = func.__module__   
    return wrapper
```

Now things work, until I add a second case:
```
@deco
def case_two(one):
    return one
```
Now we have a new problem. [The case's line number is looked up from the `__wrapped__` attribute if it exists](https://github.com/smarie/python-pytest-cases/blob/main/src/pytest_cases/common_others.py#L28), so with `wraps` things just work. Without that, though, the decorator doesn't have a way to perform the necessary extra level of introspection. The result is that all decorated functions think that the code is on the same line (inside the decorator itself) and therefore fail.

I can manually assign `wrapper.__wrapped__ = func` to address that problem, and then things get back to working again. However, now we add the final twist that I don't know how to resolve. My actual decorator modifies the function signature. Imagine something like this:
```
def deco(func):
    def wrapper(two):
        return func(one=two)
    wrapper.__name__ = func.__name__
    wrapper.__module__ = func.__module__
    wrapper.__wrapped__ = func
    return wrapper
```

Now we have a catch-22 situation. In this case assigning the `__wrapped__` attribute (or using `wraps`) is factually incorrect, and I do indeed observe errors because `pytest_cases` (correctly) infers that the argument to `wrapper` is called `one` rather than two (because I've assigned `wrapper.__wrapped__ = func`). However, if I _don't_ assign that attribute, the line number look up goes wrong again and we're back to the situation from before adding it where `pytest_cases` thinks that there are two functi0ons defined on the same line.

I'm not sure what the best way to address this is. I also realize that I'm probably pushing the boundaries of what `pytest_cases` is capable of at this point, so I completely understand if there isn't an easy solution here.

**Comment by smarie** [comment]
Nice use case @vyasr :)

I think `makefun` might be the answer to all of your needs: it is an "improved" version of functools able to deal with signature modifications while strictly preserving the behaviour (as opposed to functools.wraps, that does not raise an exception when the arguments do not comply with the signature)

Check it out here: https://smarie.github.io/python-makefun/

**Comment by vyasr** [comment]
If I understand correctly, you're suggesting that I do something like this instead:

```
def deco(func):
    def wrapper(two):
        return func(one=two)
    wrapper.__name__ = func.__name__
    wrapper.__module__ = func.__module__
    wrapper.place_as = func
    return wrapper
```

If so, that seems to replace the old issue with a new one. Here is the traceback I get by using this new version of the decorator:

```
file test_decorator.py, line 29: source code not available
file <makefun-gen-8>, line 1: source code not available
file test_decorator.py, line 19: source code not available
file test_decorator.py, line 24: source code not available
E       recursive dependency involving fixture 'two' detected
>       available fixtures: anyio_backend, anyio_backend_name, anyio_backend_options, benchmark, benchmark_weave, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, current_cases, doctest_namespace, monkeypatch, one, one_, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, test_wrapped_case_cs, testrun_uid, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, two, worker_id
>       use 'pytest --fixtures [testpath]' for help on them.
```

I suspect that this has something to do with the signature remapping, but I'm not sure. Is it somehow thinking that `wrapper` and `func` will call each other, creating a recursive loop rather than a simple linear path? 


I also tried `makefun.wraps` as you suggested

```
    @makefun.wraps(func, remove_args=("one",), prepend_args=("two",))
    def wrapper(two):
        return func(one=two)
    wrapper.place_as = func
```
which definitely gives a cleaner result that my manual application of the `functools.wraps` components that I needed (the `__name__` and `__module__`) so I'll definitely make use of it going forward. However, it still gives the same recursive dependency error as above. I assume that you weren't expecting it to resolve the error, just clean up the implementation.

**Comment by smarie** [comment]
I think that your initial error is now solved, now the error is a `pytest` fixture dependency error: pytest is telling you that there is a fixture dependency loop involving fixture `two`. So maybe fixture `two` requires another fixture, which itself requires `two`.
Fixtures can depend on other fixtures but this should be an acyclic directed graph (no cycles).

**Comment by vyasr** [comment]
Apologies if I wasn't clear, the error is from the exact MWE that I posted above, just redefining the decorator. I did not try this in the context of a larger workflow. However, as I was preparing to post the same MWE as above I realized what the problem is. Here's a MWE:

```
import pytest_cases
import makefun


@pytest_cases.fixture
def one():
    return 1


def deco(func):
    @makefun.wraps(func, remove_args=("one",), prepend_args=("two",))
    def wrapper(two):
        return func(one=two)
    wrapper.place_as = func
    return wrapper


@deco
def case_one(one):
    return one


@deco
def case_two(one):
    return one


@pytest_cases.parametrize_with_cases("cs", cases=".")
def test_wrapped_case(cs):
    assert cs == 1
```

The resulting traceback is the confusing recursion issue that I mentioned above:
```
E       recursive dependency involving fixture 'two' detected
```

However, I don't think this is the real issue, it's an obfuscating error created by the way that pytest-cases is implemented. I don't have a deep understanding, but I believe that cases are fundamentally implemented by creating specialized fixtures to inject them into the pytest dependency graph, and somewhere, the case functions are getting renamed to remove the `case_` prefix. Is that correct? Because I observe that in this MWE, if I rename `case_one` and `case_two` to `case_first` and `case_second`, I get a much more enlightening error:
```
E       fixture 'two' not found
```
which makes sense, because in my focus on redefining the decorator I forgot that in the final version of this example the actual fixture at the top needs to be named `two`, not `one`, in order for the name remapping to make sense. Renaming the fixture leads to `test_wrapped_case` correctly running on both case functions, with both case functions being defined in terms of the parameter `one` but using `deco` to wrap them in a wrapper requesting the fixture `two`, the real fixture that I want to use.

If my diagnosis about the root cause of the recursion issue is correct, perhaps there are edge cases where it could lead to conflicts between cases and fixtures? I am not sure. Feel free to close this issue if you don't think there are any action items here. Thanks for the help!

**Comment by smarie** [comment]
Very good diagnosis indeed @vyasr !

Indeed, when a case function is parametrized or requires a fixture, it is replaced with a fixture with the same name as its id (hence, `two` for `case_two`). This name is intelligently modified if it already exists, so that it does never conflict with an existing fixture or symbol. **However**, in your case, there is no existing symbol named `two`. So, `case_two` is wrapped into a fixture named `two`. Bad luck, it also requires a fixture named `two` :)

Not sure I can do much here, it would be overly complex to detect this to raise a better error message.
I guess we can now close, thanks for the feedback !

**Comment by vyasr** [comment]
Since the name is modified to avoid conflicts with fixtures that _do_ exist, I agree that there's not much to be done here. The error case of requesting a fixture that doesn't exist that also happens to conflict with the case name is definitely too specific to worry about.
