### ISSUE TITLE
Filter cases by parametrization

### ISSUE THREAD

**Issue by volcacius** [smarie/python-pytest-cases#282]
Hello,

Thanks for the excellent work with this library. I have a scenario that I can't get to work and I was wondering if there is a way around it or not. 
I have a case generator with some complicated logic and multiple `@parametrize` annotations. Depending on how it has been parametrized it should be tested by different functions. So I have been trying to use use the  `filter` argument in `@parametrize_with_cases` to filter based on how the case is currently parametrized. However, similar to #217 the id contains only the "base" and not the full thing. Is there a way to filter based on the full case id?

Thanks

**Comment by smarie** [comment]
Hi @volcacius terribly sorry for not being able to answer earlier ! :(

Unfortunately the `filter` is only used to filter out entire case functions. https://github.com/smarie/python-pytest-cases/blob/main/src/pytest_cases/case_parametrizer_new.py#L143

What you are looking for is probably reachable by adding the following line of code in your test function:

```python
@parametrize_with_cases("a")
def test_foo(a, current_cases):
    # access the case details for 'a'
    a_id, a_fun, a_params = current_cases["a"]

    if <some test based on a_params>:
        pytest.skip("This parameter is not relevant in this test")
```

Would that solve your issue ?

**Comment by volcacius** [comment]
No worries, I ended up going for something similar and it's good enough. Thanks!

**Comment by smarie** [comment]
Thanks for the feedback !
