### ISSUE TITLE
Marking cases fails when `--strict-markers` is used

### ISSUE THREAD

**Issue by jgersti** [smarie/python-pytest-cases#283]
Marking a cases with ~~`pytest.mark.skip` (and I assume for atleast any other builtin mark)~~ any mark fails with
```
'MarkDecorator' not found in `markers` configuration option
```
during collection when the cli option `--strict-markers` is used.

#### minimal example:
```python
import pytest
from pytest_cases import parametrize_with_cases

def case_a() -> str:
    return "a"

@pytest.mark.skip
def case_b() -> str:
    return "b"

@parametrize_with_cases("case", cases=".")
def test_cases(case: str)
    assert case == "a"
```
##### interpreter
python 3.10.5
##### installed packages
pytest 7.1.3
pytest-cases 3.6.13
+dependencies

**Comment by jgersti** [comment]
The offending piece of code is line 296 in the function `markinfos_to_markdecorators`: 

https://github.com/smarie/python-pytest-cases/blob/112ca87a2a2ebfe55d5a9d64902832b80d9a1c55/src/pytest_cases/common_pytest_marks.py#L275-L322

With `--strict-markers` this an illegal since only known marks can be generated with the `MarkGenerator` mechanism hidden behind `pytest.mark`.

For newer version of pytest (>=3.0) at least this can fixed by replacing 
https://github.com/smarie/python-pytest-cases/blob/112ca87a2a2ebfe55d5a9d64902832b80d9a1c55/src/pytest_cases/common_pytest_marks.py#L296
by
```python
md = MarkDecorator(Mark("dummy", [], {}))
```
Older pytest versions might need a different fix.

**Comment by smarie** [comment]
Good catch @jgersti  ! Not sure when I'll have the time to try a PR for this, as my bandwidth is fairly limited these days.
But I would be glad to review a PR if you would like to give it a go. 
Note that the nox builder tries many versions of python and pytest, so it would easily help to spot if the fix flies for other versions.
