### ISSUE TITLE
Fixture not receiving values of test parameters

### ISSUE THREAD

**Issue by maria-pia-goicoechea-lenio** [smarie/python-pytest-cases#285]
Consider this example in which I have a test (`test_nums`) which has 2 parameters: `n1` and `n2`, and a fixture (`test_fixture`) that uses `n1` and `n2`.

```python
    @fixture
    def test_fixture(self, n1, n2):
        return n1 + n2


    @parametrize_with_cases("n1, n2", cases=Cases_num)
    @pytest.mark.usefixtures("test_fixture")
    def test_nums(self, n1, n2):
        logger.info("nums test")
```

Normally, using `@pytest.mark.parametrize`, from `test_fixture` I can access the values ​​of `n1` and `n2` for each test case, but using `@parametrize_with_cases`, the `test_fixture` does not receive the correct values. (see below screenshot)

![Screen Shot 2022-10-19 at 10 15 45](https://user-images.githubusercontent.com/95311115/196701575-9bba3ed5-a06f-47bc-93a0-068d5e848eeb.png)

Is there a way to make it work?

**Comment by smarie** [comment]
Thanks @maria-pia-goicoechea-lenio  ! Very sorry to answer late.

If you actually need explicit fixtures named `n1` and `n2` parametrized with cases, you should create them explicitly before using them:

```python
from pytest_cases import fixture, parametrize_with_cases, unpack_fixture

import pytest


def case_foo(request):
    return 1, 2

@fixture
@parametrize_with_cases("a, b", cases=".")
def n1_n2(a, b):
    return a, b

n1, n2 = unpack_fixture("n1,n2", n1_n2)

@fixture
def test_fixture(n1, n2):
    return n1 + n2

@pytest.mark.usefixtures("test_fixture")
def test_nums(n1, n2):
    assert (n1 == 1) and (n2 == 2)
```

Would this solve your problem ? Otherwise could you please provide a fully reproducible example ? Indeed I cannot make this to work without getting `fixture 'n1' not found`.

**Comment by maria-pia-goicoechea-lenio** [comment]
Thanks @smarie for responding!

No, I don't want `n1` and `n2` to be fixtures. They are just parameters with some vales given from `Cases_num`
For example, let's say `n1 = 10` and `n2 = 20`

What I need to do is to access the values of `n1` and `n2` (10 and 20 in the example) inside of the `test_fixture` as I would do inside of `test_nums`

do I explain myself?

**Comment by smarie** [comment]
Hi @maria-pia-goicoechea-lenio , this is not something that is compliant with `pytest`. In pytest, **everything that you want to share** between tests, between fixtures, or between tests and fixtures, should be fixtures (Note: there is a single exception to this : placing a `parametrize` decorator on a class, which allows you to "share" parameters between all tests in a class, but not with fixtures).
So you probably really want `n1` and `n2` to be fixtures :)

But luckily, a fixture can be parametrized, and `pytest-cases` even helps you to do it more easily with its own `@fixture` decorator.

Did you try the above code ? Does it work for you ? If not, could you please explain what is not satisfying in the results ?

**Comment by smarie** [comment]
Hi @maria-pia-goicoechea-lenio , closing this in absence of response - feel free to reopen if you encountered another issue!
