### ISSUE TITLE
import_fixtures from multiple case modules

### ISSUE THREAD

**Issue by hans-d** [smarie/python-pytest-cases#295]
The flag `import_fixtures` (see also #193) works nice when importing fixtures from an external file.
```
@parametrize_with_cases(
        'a,b',
        cases=COLLECTED_CASES,
        prefix='abc_',
        import_fixtures=True,
    )
```
Or, in my case, picking up cases decorated with `@parametrize_with_cases`

```
@parametrize_with_cases('given_config', cases='.', prefix='config_')
def abc_sometesting(given_config):
    # do some extra work
    return given_config
```
However, when COLLECTED_CASES has multiple modules (files), it borks on methods using the same name.
```
E   ValueError: Cannot import fixture <function X.config_same_name at 0x1213120c0> from <module '.cases_x' from blah> as it would override an existing symbol in <module 'tests.collecting' from blah>. Please set `@parametrize_with_cases(import_fixtures=False)`
```
Wrapping them in classes wont help either. Would be nice to have those imported fixtures prefixed with something unique per module (might be a short code, as somewhere that code can be mapped to the full module).

**Comment by hans-d** [comment]
seems to be caused by something else (function returning a tuple like value)

**Comment by smarie** [comment]
Ok @hans-d ! Thanks
