### ISSUE TITLE
`ModuleNotFoundError: distutils` on Python 3.12

### ISSUE THREAD

**Issue by kdeldycke** [smarie/python-pytest-cases#297]
[`distutils` has been removed in the upcoming Python 3.12](https://docs.python.org/3.11/library/distutils.html).

So the Python 3.12.0-alpha.7 version I am trying, I get the following traceback:
```pytb
(...)
  File ".../python3.12/site-packages/pytest_cases/common_pytest_marks.py", line 8, in <module>
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'
```

Source: https://github.com/kdeldycke/click-extra/actions/runs/5061009247/jobs/9086125761#step:7:76

**Comment by smarie** [comment]
Thanks a lot @kdeldycke ! It seems that we should instead try

```python
from pkg_resources import parse_version
```

(other possibilities are discussed in https://stackoverflow.com/questions/11887762/how-do-i-compare-version-numbers-in-python but they seem a bit more risky to me)

**Comment by mportesdev** [comment]
Tried with Python 3.12.0b2:

```
$ python -c 'from distutils.version import LooseVersion; print(LooseVersion("10.0.0") > LooseVersion("2.10.0"))'
...
ModuleNotFoundError: No module named 'distutils'
```

A quick fix would be to install `setuptools`. The import will work with the following deprecation message:

```
$ pip install setuptools
...
Successfully installed setuptools-67.8.0
$ python -c 'from distutils.version import LooseVersion; print(LooseVersion("10.0.0") > LooseVersion("2.10.0"))'
<string>:1: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
True
```

Using the `packaging` library seems to work, too:

```
$ pip install packaging
...
Successfully installed packaging-23.1
$ python -c 'from packaging.version import Version; print(Version("10.0.0") > Version("2.10.0"))'
True
```

**Comment by shaunc** [comment]
Already causing a deprecation warning in python 3.11:
```py
06/15/23 21:12:24] WARNING  /home/shauncutts/.cache/pypoetry/virtualenvs/moonshine-CuQK1AVF-py3.11/lib/python3.11/site-packages/pytest_cases/com warnings.py:109
                             mon_pytest_marks.py:30: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.                
                               PYTEST_VERSION = LooseVersion(pytest.__version__)                                                                                 
                                                                                                                                                                 
                    WARNING  /home/shauncutts/.cache/pypoetry/virtualenvs/moonshine-CuQK1AVF-py3.11/lib/python3.11/site-packages/pytest_cases/com warnings.py:109
                             mon_pytest_marks.py:31: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.                
                               PYTEST3_OR_GREATER = PYTEST_VERSION >= LooseVersion('3.0.0')                                                                      
```

**Comment by jayqi** [comment]
@smarie Will this be addressed soon? The [release candidate](https://www.python.org/downloads/release/python-3120rc1/) for Python 3.12 was published last week, and the planned release for Python 3.12 is in less than 2 months. I would like to start including Python 3.12 in my test matrix. 

Also, I don't think `pkg_resources.parse_version` is the right solution. The pkg_resources package has a [notice that it is deprecated](https://setuptools.pypa.io/en/latest/pkg_resources.html). The deprecation warnings about distutils recommend using `packaging.version`, which @mportesdev demonstrated above to work as expected.

**Comment by guidovanschie-nedap** [comment]
https://peps.python.org/pep-0632/#migration-advice

> For these modules or types, use the standards-defined Python Packaging Authority packages specified:
> 
> distutils.version — use the packaging package

**Comment by jayqi** [comment]
@smarie Python 3.12 is officially released today, and pytest-cases is incompatible. It would be great if one of either #312 or #303 were adopted to fix this.
