### ISSUE TITLE
Unable uses glob filter with parametrize_with_cases

### ISSUE THREAD

**Issue by sandeep-gh** [smarie/python-pytest-cases#304]
for a fixture declared as below:

```python
def Type_HC_Active_NoStub(hc_tags):
```

Using this

```python
@parametrize_with_cases("Type_Active_NoStub", cases='.', prefix='Type_HC_Active_')
```

works, but this fails:

```python
@parametrize_with_cases("Type_Active_NoStub", cases='.', glob='*Active_NoStub')
```

In fact, I am not able to decorate use `@case(tags='foo')` and then use `has_tag='foo'`. Are these not correct usage of `parametrize_with_cases`?

**Comment by smarie** [comment]
Hi @sandeep-gh thanks for reporting and very sorry for taking so long to answer. I am progressively back on github for my duties with all the libs.

Could you please post a complete minimal test script that fails and should not ?

**Comment by smarie** [comment]
I tried and this works : 

```python
from pytest_cases import parametrize_with_cases


def Type_HC_Active_NoStub():
    return 1


@parametrize_with_cases("f", cases='.', prefix="Type", glob='*Active_NoStub')
def test_foo(f):
    assert f == 1


def test_synthesis(module_results_dct):
    assert len(module_results_dct) == 1
```

(note: you need pytest-harvest to have the `module_results_dct` fixture)
