### ISSUE TITLE
ScopeMismatch with parametrized cases

### ISSUE THREAD

**Issue by michele-riva** [smarie/python-pytest-cases#311]
Hi, here's the last one. A bit hairier.

Example to reproduce:

***cases.py***
```python
from pytest_cases import parametrize

@parametrize(arg=(1,))
def case_parametrized(arg):
    return arg
```

***conftest.py***
```python
from pytest_cases import fixture, parametrize_with_cases

@fixture(scope='session')
@parametrize_with_cases('arg', cases='cases', scope='session')
def scope_mismatch(arg):
    return arg
```

***test_scope_mismatch.py***
```python
from pytest_cases import fixture, parametrize_with_cases

@fixture
@parametrize_with_cases('arg', cases='cases')
def function_scoped(arg):
    return arg

def test_scope_mismatch(scope_mismatch):
    assert scope_mismatch == 1
```

Gives:
```
____________________________________________ ERROR at setup of test_scope_mismatch[parametrized-arg=1] _______________________________
ScopeMismatch: You tried to access the function scoped fixture parametrized with a session scoped request object, involved factories:
conftest.py:6:  def scope_mismatch(scope_mismatch_arg, request)
<makefun-gen-5>:1:  def scope_mismatch_arg(parametrized, request)
cases.py:6:  def case_parametrized(request)
```

Notice that this does **not** happen if the two fixtures are defined in the same module (either `conftest.py` or `test_scope_mismatch.py`). Also, this may be obscured by #309 or #310 if using AUTO cases.

It looks like the core of the issue is that the scope keyword argument is not passed to the .create calls here
https://github.com/smarie/python-pytest-cases/blob/ab3b7190d728b18512141b9f5f3a1c3dfc7cedf2/src/pytest_cases/fixture_parametrize_plus.py#L847-L872

In principle I can draft a PR.

**Comment by michele-riva** [comment]
Sorry, this seems a bit more complicated than just passing on scope as I suggested above. It appears to be an issue of name conflict for case-parametrized fixtures that are defined within conftest.py. The name-conflict resolution here
https://github.com/smarie/python-pytest-cases/blob/ab3b7190d728b18512141b9f5f3a1c3dfc7cedf2/src/pytest_cases/case_parametrizer_new.py#L533-L565
does not actually fix the conflict because
- we're injecting the fixture in conftest itself;
- fixtures defined in conftest.py are available for all tests.

A solution would be to prepend "conftest_" to the `case_id` (either above, or in `fixture__creation.check_name_available`), but this only partly solves the issue. In fact, assume the following test-tree structure:
```
tests/
    conftest.py
    cases.py
    test_deeper/
        conftest.py
        test_scope_mismatch.py
```

with all the modules identical to my previous example but, test_deeper/conftest.py
```python
from pytest_cases import fixture, parametrize_with_cases

@fixture(scope='class')
@parametrize_with_cases('arg', cases='cases', scope='class')
def scope_mismatch_deeper(arg):
    return arg
```

While scope_mismatch_deeper is being parametrized, `target_host.__name__ == 'conftest'` (and not 'test_deeper.conftest') because test_deeper/conftest.py is currently being imported. This would simply duplicate the `'conftest_'+case_id` name, leading to another scope mismatch.

The ideal solution would be to have a `list_all_fixtures_in_conftests` function to be added to the existing_fixture_names. However, I know too little of pytest & pytest-cases to suggest an implementation.

**Comment by michele-riva** [comment]
Sorry for the spam. Perhaps a simpler solution than a `list_all_fixtures_in_conftests` would be to include also the scope in the base name to be checked (only if the fixture is injected in a conftest.py).

E.g.,
```python
if target_host.__name__ == 'conftest':
    case_id = 'conftest_' + case_id + '_with_scope_' + scope
```

This has the disadvantage of making names longer. If this sounds acceptable, I can also include it in the PR.

**Comment by smarie** [comment]
Thanks @michele-riva for reporting this issue and working on a solution !
I am sorry that I still not found the bandwidth to review this, but yes please feel free to open a PR in whatever state it is (just prefix it [WIP] or tag it as draft while it is not ready for review).

This is definitely one of the nasty aspects of pytest-cases: it generates a lot of fixtures behind the scenes.

Does your issue also happen when the cases are in the same file than the test file, and cases are just imported with `cases='.'` ? If so I recommend to create the test as such, it is simpler.

**Comment by michele-riva** [comment]
> I am sorry that I still not found the bandwidth to review this, but yes please feel free to open a PR in whatever state it is (just prefix it [WIP] or tag it as draft while it is not ready for review).

No worries, I'm also pretty toasted. I have some code in a fork, and I'll prepare a PR today.

> Does your issue also happen when the cases are in the same file than the test file, and cases are just imported with `cases='.'` ? If so I recommend to create the test as such, it is simpler.

Good question. I'd have to try it out. I'll update the tests if this is the case.

**Comment by michele-riva** [comment]
> Does your issue also happen when the cases are in the same file than the test file, and cases are just imported with `cases='.'` ? If so I recommend to create the test as such, it is simpler.

Looks like the issue does not show up for cases defined in the same file. I'll have to go for the more complicated structure.

**Comment by michele-riva** [comment]
I've just opened #317, which should fix this. Happy to discuss edits if needed.
