### ISSUE TITLE
pytest-case produces a lot of debug logs

### ISSUE THREAD

**Issue by kfrydel** [smarie/python-pytest-cases#336]
It looks like this change: https://github.com/smarie/python-pytest-cases/commit/0d257b26e2de9bea2ee259f859580462b36811db#diff-9b37d16b82c957964061f9038c8a206519d73a723c977f9821054a7d522793a1R44 enabled DEBUG messages. Is it intentional?
We started to have megabytes of additional output in our tests.

**Comment by smarie** [comment]
Indeed ! Let me revert this

**Comment by kfrydel** [comment]
Thank you!

**Comment by smarie** [comment]
Unfortunately I can't release this for now because of an issue between pytest-harvest and pytest 8

So for now you can simply use `pip install git+https://github.com/smarie/python-pytest-cases.git`
and later these days I'll make a proper 3.8.4

**Comment by smarie** [comment]
I finally did it. 3.8.4 should solve this issue. Sorry again !
