### ISSUE TITLE
Issue in pytest-cases 1.8.1 with markers

### ISSUE THREAD

**Issue by browniebroke** [smarie/python-pytest-cases#46]
First of all, thanks for this neat library, it has simplified our tests quite a bit for [cookiecutter-django](https://github.com/pydanny/cookiecutter-django/blob/master/tests/test_cookiecutter_generation.py).

I'm not sure if I missed a change in 1.8 or if it's an actual bug, but it seems that 1.8.1 is not playing nicely with pytest markers. We use markers to spread markers over multiple workers on our CI:

- One worker runs tests marked with `black`
- One worker runs tests marked with `flake8`
- A last worker runs all unmarked tests `flake8`

We basically have 3 test function which all use a [pretty big parametrized fixture](https://github.com/pydanny/cookiecutter-django/blob/d2f3891fe1d965dc5f0bfc6f208ddb2bd444d4dc/tests/test_cookiecutter_generation.py#L32-L61).

Until <1.8.1, the black output [was running in ~8 mins](https://travis-ci.org/pydanny/cookiecutter-django/jobs/546085072). With 1.8.1, it takes ~20 mins to run and judging [by the output](https://travis-ci.org/pydanny/cookiecutter-django/jobs/545959913), it looks like a lot more test cases are executed.

I tried to bump to 1.8.0 and the output is [consistent with the existing](https://travis-ci.org/pydanny/cookiecutter-django/jobs/546085735) behaviour and execution around ~9mins.

Am I still using the library as it's intended or is there a regression in 1.8.1?

**Comment by smarie** [comment]
Thanks for the feedback !

Two main things changed indeed

 - the `pytest` optimized order for session- and module-scoped fixtures was disabled thanks to the `pytest_collection_modifyitems` hook. I already noted in #45 that this was too dangerous and should be only done with an explicit commandline option. This should only have an impact about the number of setups/teardowns, not about the number of tests
 - the fixtures that have no parameters at all are now parameterized with either a single or two values, depending on whether they are always used or not in tests where fixture unions are used. I would rather bet that this one had the side effects that you mention.

I'll try to fix both asap, probably on monday.

**Comment by smarie** [comment]
I found the issue, it was with the reordering. Let me know if 1.9.0 fixes your problem (it should)

**Comment by browniebroke** [comment]
Yea, looks like the execution time and load spreading is back to usual figures, thanks for the quick fix!

**Comment by smarie** [comment]
you're welcome, thanks for the feedback !
