### ISSUE TITLE
Make fixtures available without explicitly importing them from conftest.py

### ISSUE THREAD

**Issue by yashtodi94** [smarie/python-pytest-cases#60]
Currently, I need to explicitly import a fixture or write the fixture in the same file as the test to use them in `fixture_ref()` of `pytest_parametrize_plus()`

```
def fixture():
    # Fixture code

def test_foo():
    # test code
```

Pytest automatically imports the fixtures defined in `conftest.py` and makes them available for all test files to be used as arguments in test functions. This does not seem possible when I use `fixture_ref` in `pytest_parametrize_plus`.

Is there a way to do this that I am missing out? If not, is it possible to have this feature?

Thanks

**Comment by smarie** [comment]
Thanks for the feedback. This sounds like a bug, I will investigate

**Comment by smarie** [comment]
I can not reproduce the bug :(

Indeed if I define a fixture in `contest.py` for example

```python
@pytest.fixture
def global_fixture():
    return 'global'
```

I can then use it in any test file:

```python
@pytest_parametrize_plus('main_msg', ['nothing', fixture_ref('global_fixture')])
@pytest.mark.parametrize('ending', ['?', '!'])
def test_prints(main_msg, ending):
    print(main_msg + ending)
```

Yields:

```
test_fixture_in_parametrize_basic.py::test_prints[test_prints_main_msg_is_0-nothing-?] 
test_fixture_in_parametrize_basic.py::test_prints[test_prints_main_msg_is_0-nothing-!] 
test_prints[test_prints_main_msg_is_global_fixture-?] 
test_prints[test_prints_main_msg_is_global_fixture-!] 
```

So there is maybe something more complex in the issue that you spotted, can you investigate ?

**Comment by yashtodi94** [comment]
I think the issue is that I am using the actual value instead of passing the name of the fixture as string to `fixture_ref()`

I am using this:

`@pytest_parametrize_plus('main_msg', ['nothing', fixture_ref(global_fixture)])`

instead of:

`@pytest_parametrize_plus('main_msg', ['nothing', fixture_ref('global_fixture')])`

Let me confirm if it works.

**Comment by smarie** [comment]
Both work for me - either using the symbol or the fixture name.

Internally the fixture name is retrieved using [`get_fixture_name`](https://github.com/smarie/python-pytest-cases/blob/afd87921ec74b054a01f8a4d73365961c3cdff22/pytest_cases/common.py#L27). Could you check what is the output of `get_fixture_name(global_fixture)` in your case ? It should be `'global_fixture'`.

**Comment by yashtodi94** [comment]
This is what I get:

```
    @pytest_parametrize_plus('main_msg', [('nothing', fixture_ref(global_fixture))])
E   NameError: name 'global_fixture' is not defined
```

**Comment by smarie** [comment]
I updated the travis configuration to see if this is related to pytest 5: https://travis-ci.org/smarie/python-pytest-cases/builds/587077162

**Comment by smarie** [comment]
Can you please send the full stack trace of your error message ?

**Comment by yashtodi94** [comment]
```
# conftest.py

@pytest.fixture
def foobar_1(foobar_2):
    return foobar_2


@pytest.fixture
def foobar_2():
    return 2


@pytest.fixture
def global_fixture():
    return 'global'
```

```
# test file


@pytest_parametrize_plus('main_msg', [('nothing', fixture_ref(global_fixture))])
def test_prints():
    print('foo')

@pytest_parametrize_plus('val, expected', [(fixture_ref('foobar_1'), fixture_ref('foobar_1'))])
def test_prints_2(val, expected):
    assert val == expected
```

Stack Trace (there are other items collected too, can be ignored): 
```
========================================================================================= test session starts ==========================================================================================
platform darwin -- Python 3.7.4, pytest-5.1.2, py-1.8.0, pluggy-0.13.0 -- /Users/yash/.virtualenvs/campaigner/bin/python3.7
cachedir: .pytest_cache
rootdir: /Users/yash/Sojern/python/campaigner
plugins: cov-2.7.1, mock-1.10.4, cases-1.11.2
collected 22 items / 1 errors / 22 deselected                                                                                                                                                          

================================================================================================ ERRORS ================================================================================================
__________________________________________________________________________ ERROR collecting campaigner/tests/test_pb_utils.py __________________________________________________________________________
tests/test_pb_utils.py:186: in <module>
    @pytest_parametrize_plus('main_msg', [('nothing', fixture_ref(global_fixture))])
E   NameError: name 'global_fixture' is not defined
=========================================================================================== warnings summary ===========================================================================================
/Users/yash/.virtualenvs/campaigner/lib/python3.7/site-packages/pytest_cases/plugin.py:128
  /Users/yash/.virtualenvs/campaigner/lib/python3.7/site-packages/pytest_cases/plugin.py:128: UserWarning: WARNING the new order is not taken into account !!
    warn("WARNING the new order is not taken into account !!")

-- Docs: https://docs.pytest.org/en/latest/warnings.html
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================= 22 deselected, 1 warnings, 1 error in 0.53s ==============================================================================
```

**Comment by yashtodi94** [comment]
> Can you please send the full stack trace of your error message ? I guess that you receive the same error in both cases (string or symbol) ?

The string part worked for me. I guess I am going to continue with that. Thanks.

**Comment by smarie** [comment]
The solution is very simple :) you forgot to import the symbol so the python interpreter is not happy: in your test file simply add `from <xxx>.conftest import global_fixture`.

**Comment by yashtodi94** [comment]
> It seems that you forgot to import the symbol so the python interpreter is not happy: in your test file simply add `from <xxx>.conftest import global_fixture` and it should work as expected.
> 
> Note: if you use PyCharm or another similar IDE it should tell it to you already in the editor

Haha, I know this solution (Said that in the very first line of the thread :)).

Till now I was making it work with the `import` itself. But I have a lot of fixtures and didn't want to import everyone or all of them unnecessarily (coz `pytest` does it anyway).

The string solution works fine with me.

But it would be better if I do not need to explicitly.

**Comment by smarie** [comment]
Ok then, no worries ! 

> But it would be better if I do not need to explicitly.

Unfortunately we are limited by the language capabilities here: if you do not import it, you can only use a new symbol if it is a new variable, function or class definition, or an input name.

I should maybe even prevent users to pass symbols so that there is only one way to do it (the string name).

Anyway thanks for the feedback !
