### ISSUE TITLE
Unable to install in tox env - ImportError: No module named six

### ISSUE THREAD

**Issue by raddessi** [smarie/python-pytest-cases#65]
Hey, this looks great but I'm unable to install this locally in my tox test envs. On installation of the package pip tries to run setup.py but then complains that six is not installed. Ive tried to add a pyproject.toml with `dependencies` and `build-system` sections to no avail, have you seen this yourself yet?

Here is a trimmed `tox.ini` file I can recreate with:

```
[tox]
envlist = something-py27
skipsdist = true

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
deps =
    pytest-cases
    pytest-cov
    pytest-datafiles
    pytest-lazy-fixture
    pytest-pythonpath
    pytest-xdist

    py27: pytest==4.6.5
    py36: pytest==5.2.1


commands =
    pytest -v {posargs}
```

**Comment by smarie** [comment]
Someone else already reported something similar for another of my projects and proposed a `pyproject.toml`: https://github.com/smarie/python-makefun/pull/44/files

From current build (travis) I do not rely on a `pyproject.toml`, I just install the requirements at https://github.com/smarie/python-pytest-cases/blob/master/ci_tools/requirements-pip.txt before actually using.

Maybe you could get inspired from the PR above to propose an equivalent for this project ? Let me know if I can help.

**Comment by raddessi** [comment]
I actually did fork this off and try to make this work with a `pip install git+https://blah` using both setup.ini and then pyproject.toml but I couldn't get it to install the packages `setuptools_scm` or `six` before trying to run setup.py, which would then fail since they were missing. I can dig more when I have time, I was hoping you would know more than I do about packaging and there was just something I was missing.

**Comment by raddessi** [comment]
Actually.. I may have a working change at the moment. I think this issue is fixed in the fork and now another package has the same exact issue and I just wasn't reading the failing package name correctly. Let me work on this for a bit and I'll send a PR if this is resolved. Thanks!

**Comment by raddessi** [comment]
It works! pytest-cases was pulling in decopatch which had the same issue, and I wasn't reading the output correctly and assumed it was the same failure from pytest-cases. PRs incoming

**Comment by smarie** [comment]
cool, thanks ! I answered in the PRs

**Comment by raddessi** [comment]
Do you release new versions to pypi regularly?

**Comment by smarie** [comment]
sorry I thought you were working from sources - yes, it is fully automated on tag so I can do it anytime if needed

**Comment by smarie** [comment]
I dont know why I thought that btw since the stacktrace we pretty explicit :)

**Comment by smarie** [comment]
decopatch 1.4.7 and pytest-cases 1.11.6 released. Let me know if this closes the ticket. Thanks again !

**Comment by raddessi** [comment]
Oh no problem, there was plenty of confusion on my side as well ;) Yes this works perfectly now! tox builds from pypi just with the name pytest-cases, I will close this out. Great work on this project and thank you for the quick responses btw, have a great week!

**Comment by smarie** [comment]
Thanks for the feedback! Great week to you too
