### ISSUE TITLE
Collision with pytest_asyncio - related to FixtureClosureNode.append

### ISSUE THREAD

**Issue by ze-phyr-us** [smarie/python-pytest-cases#68]
Hi,
I think the stub (non)implementation of `FixtureClosureNode`'s list interface is causing a problem when [pytest-asyncio](https://pypi.org/project/pytest-asyncio/) is also used. This simple test passes when `pytest-cases` is not installed:

```python
import pytest

@pytest.mark.asyncio
async def test_x():
    assert True
```

However, as soon as I install `pytest-cases` the same test fails:

```
$ pytest test_asyncio.py
================================================ test session starts ================================================
platform linux -- Python 3.7.0, pytest-5.2.2, py-1.8.0, pluggy-0.13.1 -- /usr/local/bin/python
cachedir: .pytest_cache
benchmark: 3.2.2 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /usr/src/app, inifile: pytest.ini
plugins: cases-1.11.8, benchmark-3.2.2, reporter-0.2.0, asyncio-0.10.0, cov-2.8.1, test-groups-1.0.3, logwood-3.5.0, aiohttp-0.3.0
collected 1 item

test_asyncio.py::test_x FAILED

===================================================== FAILURES ======================================================
______________________________________________________ test_x _______________________________________________________

pyfuncitem = <Function test_x>

    @pytest.mark.tryfirst
    def pytest_pyfunc_call(pyfuncitem):
        """
        Run asyncio marked test functions in an event loop instead of a normal
        function call.
        """
        for marker_name, fixture_name in _markers_2_fixtures.items():
            if marker_name in pyfuncitem.keywords \
                    and not getattr(pyfuncitem.obj, 'is_hypothesis_test', False):
>               event_loop = pyfuncitem.funcargs[fixture_name]
E               KeyError: 'event_loop'

/usr/local/lib/python3.7/site-packages/pytest_asyncio/plugin.py:150: KeyError
================================================= warnings summary ==================================================
test_asyncio.py::test_x
  /usr/local/lib/python3.7/site-packages/pytest_cases/plugin.py:132: UserWarning: WARNING some code tries to add an item to the fixture tree, this will be IGNORED !! Item: event_loop
    warn("WARNING some code tries to add an item to the fixture tree, this will be IGNORED !! Item: %s" % item)

-- Docs: https://docs.pytest.org/en/latest/warnings.html

----------- coverage: platform linux, python 3.7.0-final-0 -----------
Coverage HTML written to dir .cache/coverage-report

=========================================== 1 failed, 1 warnings in 8.47s ===========================================
```

That UserWarning in there is telling, I think. But I have no idea how to fix this :)

The problem goes away when you explicitly use the `event_loop` fixture in the test:

```python
@pytest.mark.asyncio
async def test_x(event_loop):
    assert True
```

Unfortunately that's not what you want in the majority of pytest-asyncio tests, because you don't want to care about the particular event loop instance at all.

**Comment by smarie** [comment]
Thanks for reporting ! I was able to reproduce it.

**Comment by smarie** [comment]
Unfortunately this is due to the fact that `pytest_asyncio` is injecting a fixture dependency in a way that is not "standard" (i.e. it does not add a parameter to the function ; instead it adds the fixture name to the fixture closure).

I am not sure if fixing this will be easy, probably not. How "critical" is the issue for now ? Does the workaround work for you today ? If so I'd like to postpone fixing this to the time where I'll discuss with pytest team about inserting merging the "fixture unions" feature of pytest cases in pytest. Indeed this is a very low level hack that should not stay outside for ever.

**Comment by ze-phyr-us** [comment]
Thank you for looking into this. We have 500+ tests utilising pytest-asyncio, so adding that unwanted `event_loop` argument to all of them would be quite sad, not to mention adding all those `# pylint: disable=unused-argument` comments 😞 

If pytest-asyncio's way of injecting the dependency is not standard, is it perhaps worth opening an issue with them?

**Comment by smarie** [comment]
Indeed. I'll have to check this "non standard" assertion, I might be wrong. `pytest` API is quite broad so there are often many ways to do the same thing, several more "hacky-looking" than others - that may not mean that this is not "standard". I'll look into this, maybe with the help from pytest team

**Comment by smarie** [comment]
I managed to make this work :) should ship in 1.11.9 when travis has built

**Comment by ze-phyr-us** [comment]
Thanks a lot! Works for me too.
