### ISSUE TITLE
Is it possible to parametrize a fixture that returns a list?

### ISSUE THREAD

**Issue by asharmarx** [smarie/python-pytest-cases#73]
Hello everyone,

I was wondering if it is possible to parametrize a fixture that returns a list using some combination of parametrize_plus, fixture_ref, and/or unpack_into.

For ex:
```python
@pytest.fixture()
def method_a():
    list_a = ['a', 'b', 'c', 'd']
    return list_a

@fixture_plus
@parametrize_plus('list_a', fixture_ref(method_a))
def print_list_items(list_a):
    return print(list_a)
```

Is something like this possible? 

I am running Python 3.7.3 and pytest-cases version 1.12.0.

**Comment by smarie** [comment]
Thanks for asking ! 

Indeed the roles and responsibilities of fixtures and parameters in pytest are not very clear to get. Please check first this post : https://stackoverflow.com/questions/42228895/how-to-parametrize-a-pytest-fixture/56871701#56871701

It should help you understand why what you are asking for is unfortunately not possible :(

**Comment by smarie** [comment]
Actually this one is even clearer: https://stackoverflow.com/questions/50231627/python-pytest-unpack-fixture/56865893#56865893

**Comment by asharmarx** [comment]
Wow, thank you so much! Though it's a bummer I can't achieve what I wanted, I now learned something more about pytest.

**Comment by smarie** [comment]
Note that you can achieve what you want - you just cannot with fixtures "out of the box". Why do you absolutely need this list to be a (*dynamically* created) fixture ? You could instead create it as a variable anywhere in the scripts (created before the collection phase ends) and use this variable to source your pytest parameters.
