### ISSUE TITLE
ValueError: This should not happen anymore

### ISSUE THREAD

**Issue by Sauci** [smarie/python-pytest-cases#76]
Hello,
I'm trying to use nested ```fixture_plus``` into my [tests](https://github.com/Sauci/pydbc/blob/master/test_grammar.py), but I get a **ValueError**, with message **This should not happen anymore**, raised from *plugin.py*, line 387. Bellow, a code snippet to reproduce this issue. I hope I'm not doing something wrong...
```python
import pytest
import pytest_cases

doubles = [0.0, -1.0, 1.0]
char_strings = ['"s"', '"_"']
c_identifiers = ['_', '_c']


class DummyClass(object):
    def __init__(self, *args, **kwargs):
        pass


@pytest_cases.fixture_plus()
@pytest.mark.parametrize('double', doubles)
@pytest.mark.parametrize('char_string', char_strings)
def value_table_description(double, char_string):
    return '{} {}'.format(double, char_string), DummyClass(double, char_string)


@pytest_cases.fixture_plus()
@pytest.mark.parametrize('value_table_name', c_identifiers)
@pytest.mark.parametrize('value_descriptions_count', [1, 2])
@pytest_cases.parametrize_plus('value_description_0', [pytest_cases.fixture_ref('value_table_description')])
@pytest_cases.parametrize_plus('value_description_1', [pytest_cases.fixture_ref('value_table_description')])
def value_table(value_table_name, value_descriptions_count, value_description_0, value_description_1):
    value_description_0_string, value_description_0_value = value_description_0
    value_description_1_string, value_description_1_value = value_description_1
    value_descriptions_string = [value_description_0_string, value_description_1_string][:value_descriptions_count]
    value_descriptions_value = [value_description_0_value, value_description_1_value][:value_descriptions_count]
    return ('VAL_TABLE_ {} {} ;'.format(value_table_name, ' '.join(value_descriptions_string)),
            DummyClass(value_table_name, value_descriptions_value))


@pytest_cases.fixture_plus()
@pytest.mark.parametrize('value_tables_count', [1, 2])
@pytest_cases.parametrize_plus('value_table_0', [pytest_cases.fixture_ref('value_table')])
@pytest_cases.parametrize_plus('value_table_1', [pytest_cases.fixture_ref('value_table')])
def value_tables(value_tables_count, value_table_0, value_table_1):
    value_table_0_string, value_table_0_value = value_table_0
    value_table_1_string, value_table_1_value = value_table_1
    value_tables_string = '\n'.join([value_table_0_string, value_table_1_string][:value_tables_count])
    value_tables_value = [value_table_0_value, value_table_1_value][:value_tables_count]
    return value_tables_string, DummyClass(value_tables_value)


@pytest_cases.parametrize_plus('vts', [pytest_cases.fixture_ref('value_tables')])
def test_value_tables_node(vts):
    value_table_string, value_table_value = vts
    p = DummyClass(value_table_string)
    assert isinstance(p.ast.value_tables, list)
    assert p.ast.value_tables[0] == value_table_value

```

Here, the full stack trace:
Testing started at 15:27 ...
C:\Users\lmbsog0\AppData\Local\Programs\Python\Python38-32\python.exe C:\Users\lmbsog0\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-1\201.6251.24\plugins\python\helpers\pydev\pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 57573 --file C:\Users\lmbsog0\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-1\201.6251.24\plugins\python\helpers\pycharm\_jb_pytest_runner.py --path C:/git/pydbc/test_dummy.py
pydev debugger: process 14284 is connecting

Connected to pydev debugger (build 201.6251.24)
Launching pytest with arguments C:/git/pydbc/test_dummy.py in C:\git

============================= test session starts =============================
platform win32 -- Python 3.8.2, pytest-5.4.1, py-1.8.0, pluggy-0.13.1 -- C:\Users\lmbsog0\AppData\Local\Programs\Python\Python38-32\python.exe
cachedir: .pytest_cache
rootdir: C:\git\pydbc
plugins: cases-1.12.3
collecting ... 
test_dummy.py:None (test_dummy.py)
C:\Users\lmbsog0\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pluggy\hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
C:\Users\lmbsog0\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pluggy\manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
C:\Users\lmbsog0\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pluggy\manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
C:\Users\lmbsog0\AppData\Local\Programs\Python\Python38-32\lib\site-packages\_pytest\python.py:248: in pytest_pycollect_makeitem
    res = list(collector._genfunctions(name, obj))
C:\Users\lmbsog0\AppData\Local\Programs\Python\Python38-32\lib\site-packages\_pytest\python.py:403: in _genfunctions
    definition = FunctionDefinition.from_parent(self, name=name, callobj=funcobj)
C:\Users\lmbsog0\AppData\Local\Programs\Python\Python38-32\lib\site-packages\_pytest\python.py:1448: in from_parent
    return super().from_parent(parent=parent, **kw)
C:\Users\lmbsog0\AppData\Local\Programs\Python\Python38-32\lib\site-packages\_pytest\nodes.py:170: in from_parent
    return cls._create(parent=parent, **kw)
C:\Users\lmbsog0\AppData\Local\Programs\Python\Python38-32\lib\site-packages\_pytest\nodes.py:87: in _create
    return super().__call__(*k, **kw)
C:\Users\lmbsog0\AppData\Local\Programs\Python\Python38-32\lib\site-packages\_pytest\python.py:1430: in __init__
    fixtureinfo = self.session._fixturemanager.getfixtureinfo(
C:\Users\lmbsog0\AppData\Local\Programs\Python\Python38-32\lib\site-packages\_pytest\fixtures.py:1286: in getfixtureinfo
    initialnames, names_closure, arg2fixturedefs = fm.getfixtureclosure(
C:\Users\lmbsog0\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pytest_cases\plugin.py:580: in getfixtureclosure
    fixturenames_closure_node.build_closure(_init_fixnames, ignore_args=ignore_args)
C:\Users\lmbsog0\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pytest_cases\plugin.py:266: in build_closure
    self._build_closure(self.fixture_defs_mgr, initial_fixture_names, ignore_args=ignore_args)
C:\Users\lmbsog0\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pytest_cases\plugin.py:344: in _build_closure
    self.split_and_build(fixture_defs_mgr, fixname, fixturedefs, alternative_f_names,
C:\Users\lmbsog0\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pytest_cases\plugin.py:411: in split_and_build
    new_c._build_closure(fixture_defs_mgr, [f], ignore_args=ignore_args)
C:\Users\lmbsog0\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pytest_cases\plugin.py:344: in _build_closure
    self.split_and_build(fixture_defs_mgr, fixname, fixturedefs, alternative_f_names,
C:\Users\lmbsog0\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pytest_cases\plugin.py:413: in split_and_build
    new_c._build_closure(fixture_defs_mgr, pending_for_child, ignore_args=ignore_args)
C:\Users\lmbsog0\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pytest_cases\plugin.py:344: in _build_closure
    self.split_and_build(fixture_defs_mgr, fixname, fixturedefs, alternative_f_names,
C:\Users\lmbsog0\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pytest_cases\plugin.py:387: in split_and_build
    raise ValueError("This should not happen anymore")
E   ValueError: This should not happen anymore
collected 0 items / 1 error

Thanks in advance for your feedback

**Comment by smarie** [comment]
Thanks for reporting ! I'll have a look, indeed this should not happen anymore.

**Comment by smarie** [comment]
I managed to fix the issue, I will release it soon. I end up with `AttributeError` in your test example, but I guess this is now just a human mistake, not related to the engine:

```
vts = ('VAL_TABLE_ _ 0.0 "s" ;', <pytest_cases.tests.issues.test_issue_so_76.DummyClass object at 0x000002698DA869B0>)

    @pytest_cases.parametrize_plus('vts', [pytest_cases.fixture_ref('value_tables')])
    def test_value_tables_node(vts):
        value_table_string, value_table_value = vts
        p = DummyClass(value_table_string)
>       assert isinstance(p.ast.value_tables, list)
E       AttributeError: 'DummyClass' object has no attribute 'ast'

test_issue_so_76.py:51: AttributeError
```

**Comment by smarie** [comment]
1.12.4 will be available once [the build has completed](https://travis-ci.org/github/smarie/python-pytest-cases) and it should fix this. Let me know if it is not the case !

**Comment by Sauci** [comment]
Thank you very much, it works now
