### ISSUE TITLE
Name param value can automatic generated by the kwargs

### ISSUE THREAD

**Issue by liushanguo** [smarie/python-pytest-cases#77]
The `cases_generator` decorator  `name` param is too long?
I think it's can be automatic generated by the kwargs

Like this:

    from decopatch import function_decorator
    from pytest_cases import cases_generator
 
    @function_decorator 
    def wrap_cases_generator(names=None, lru_cache=False, **kwargs):
        if names is None:
            names = ''
            for key in kwargs.keys():
                s = '{key_name}={{{key_name}}}, '.format(key_name=key)
                names += s

    return cases_generator(names, lru_cache, **kwargs)

**Comment by smarie** [comment]
Hi @liushanguo and thanks for this ticket ! 

Indeed I seem to have forgotten to include a default behaviour when `names=None`. I'll fix this right away.

**Comment by smarie** [comment]
This should be fixed in 1.13.0 that will be released on pypi when the build [completes](https://travis-ci.org/github/smarie/python-pytest-cases/builds/668770976)

**Comment by liushanguo** [comment]
thanks !
