### ISSUE TITLE
Enforce file naming pattern: automatically get cases from file named `test_xxx_cases.py`

### ISSUE THREAD

**Issue by smarie** [smarie/python-pytest-cases#91]
We suggest this pattern in the doc, we could make it a default.

**Comment by saroad2** [comment]
Awesome solution! personally, I prefer much better the *cases_XXX.py*. The reason for that is that paths starting with *test_* are for, well, tests (not cases)!  Starting with the *cases_* prefix will make it much clearer.

What do you think?

**Comment by smarie** [comment]
Well to be honest my first implementation in the early days was just like you propose :) 

But then I found out that my test folders were "hard" to manage because the file containing the cases was sitting "far" from its test counterpart in the sorting order of my IDE (PyCharm), which was alphabetical. Still, I agree that this is much more nicer to read! Maybe I'll make that one the default (cases_xxx), and propose a quick boolean argument to easily switch to the other one (test_xxx_cases). I'll think about it. 

And also now I have another "loose" reason for preferring the "test_xxx_cases.py" option: if users define a fixture in the file, it will be automatically taken into account by pytest. Otherwise, I'll have to find a way to manually register it with the pytest API. I'm probably being lazy here :)
