### ISSUE TITLE
alternate approach as cases inside class

### ISSUE THREAD

**Issue by jnoortheen** [smarie/python-pytest-cases#93]
I really like this library but it seems to require lot of boilerplate code to get running. 

Can we have a class based approach as well to the existing approaches? 
What do you think about the following way?.
```py

class TestDescribeTest():
  def case_one(self, fixture1, fixture2, fixture3):
     return input, output, err
  def case_two(self, fixture2, fixture3):
    return input, output, err
  def test_function(self, input, output, err):
    # test body
```

 I know I can just put this inside  generate_tests to parameterize the test, but not sure, how to pass the parameters from the case functions and make the case functions behave like fixture functions. What are your opinions?

**Comment by smarie** [comment]
@jnoortheen thanks for the feedback ! 

I agree with you - this is why I am in the process of making the experience closer to pytest. (See #90 )
This should happen within one or two weeks, so I suggest that we take this conversation again when it (and the associated new readme) is done.

Sorry for delaying, and thanks for your patience !

**Comment by smarie** [comment]
@jnoortheen sorry for taking so much time but I finally release version 2.0.0 today. It should provide a good answer to your concerns. Let me know !

**Comment by jnoortheen** [comment]
It looks great Thanks :)
